### PR TITLE
JIT caching updates

### LINKED ISSUE #798: Ensure jitted functions can be cached
If we can cache them, we can get rid of of some nasty latencies introduced by #706, which is important for a smooth user experience.

### PR DESCRIPTION
**Pull request by sk1p**
Fixes #798 once numba properly caches functions with w/ closures over other functions. Independent from this, we can decide if we want to add a work-around to make these functions cacheable. 

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if
changes were made to the GUI)

### CODE REVIEW

**Comment by sk1p** [comment]
For some reason, with the cache warming enabled, the tests seem to fail more consistently. Great. I'll postpone merging this until I know why.

**Comment by sk1p** [comment]
> For some reason, with the cache warming enabled, the tests seem to fail more consistently. Great. I'll postpone merging this until I know why.

This should now behave better, as we should only have a single jit compilation when re-using the dask worker and scheduler.

**Comment by sk1p** [comment]
Tests are still not stable, but this time I can reproduce the issue with Python 3.6 locally.

**Comment by sk1p** [comment]
Tracked down to https://github.com/tornadoweb/tornado/issues/2034 https://github.com/dask/distributed/issues/4356, proposed fix at https://github.com/tornadoweb/tornado/pull/2963

**Comment by uellue** [comment]
Wow, nice catch! 🚀

**Comment by uellue** [comment]
So, do we have to wait for upstream or can we circumvent this in LiberTEM?

**Comment by sk1p** [comment]
> So, do we have to wait for upstream or can we circumvent this in LiberTEM?

This one is hard to circumvent, as the problem is caused by a centrally used utility function. I think it could be possible to make the failure less likely, by just taking a different code path. I'll need to try a few things, and I'll come back to this PR.

**Comment by sk1p** [comment]
Looks like that worked, both Mac and Win Py36 build finished.

**Comment by uellue** [comment]
Nice to see that it goes around that issue! 🎉 

Is the low test coverage an artifact from not collecting coverage from Dask, or could we still add test cases that improve coverage?

**Comment by sk1p** [comment]
> Is the low test coverage an artifact from not collecting coverage from Dask, or could we still add test cases that improve coverage?

It was, but now I've added a test case using the `InlineJobExecutor` together with the web API, which allows us to collect coverage for this case. For some ideas on a full fix, see #545. This should now be ready to merge.

**Comment by uellue** [comment]
Awesome, merging!

**Comment by sk1p** [comment]
> Tracked down to [tornadoweb/tornado#2034](https://github.com/tornadoweb/tornado/issues/2034) [dask/distributed#4356](https://github.com/dask/distributed/issues/4356), proposed fix at [tornadoweb/tornado#2963](https://github.com/tornadoweb/tornado/pull/2963)

Btw. this was recently merged, so hopefully will be fixed for good on the next release of tornado.

**Pull request merged**
