### PR TITLE
Improve cluster UX after error

### PR DESCRIPTION
**Pull request by twentyse7en**
Cluster connection form re-open with parameters user submitted.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if
changes were made to the GUI)

### CODE REVIEW

**Comment by twentyse7en** [comment]
@skip is this okay?

**Comment by sk1p** [comment]
Looks fine, I'll give it a quick test run

**Comment by twentyse7en** [comment]
How can I verify if local storage is updated?

**Comment by sk1p** [comment]
> How can I verify if local storage is updated?

Check the "Applications" tab in the devtools:

image

**Comment by twentyse7en** [comment]
Last time for successful Local connection, `numWorkers` would replace `address` in `lastConnection`. So only connection type is saved for Local connection.

**Comment by twentyse7en** [comment]
is there anything else to do @sk1p

**Comment by sk1p** [comment]
Don't think so, not at the office right now, will have a look / merge later. Thanks!

**Pull request merged**
