### PR TITLE
WIP: Executor based on concurrent.futures

### LINKED ISSUE #1146: Threaded single host dask executor
This is required to work well with Dask arrays created with `dask.array.from_array()`: #1137 

Things to consider:

- [x] Make sure relevant code is tested against all executors, also relevant for #983 
- [x] Make choice of executor easier for users and clear which to use for what

### PR DESCRIPTION
**Pull request by uellue**
Based on #1137 to help with testing the integration, to be rebased
once that is merged!

Closes #1146

TODO:

- [x] Proper benchmarking, verify on `da.from_array(np.memmap(...))` with a very large file
- [ ] General testing strategy for multiple executors, refs also #983
- [ ] Easy selection of executor in `Context()

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by matbryan52** [comment]
That was fast! I will try to test this out this afternoon, I'm stuck on something else for the moment.

**Comment by uellue** [comment]
## Benchmark results on ptycho (single AMD EPYC 7F72, current Debian stable, Python 3.9)

``` 
-------------------------------------------------------------------------------------------- benchmark 'dask from_array': 24 tests ---------------------------------------------------------------------------------------------
Name (time in ms)                                         Min                   Max                  Mean             StdDev                Median                IQR            Outliers      OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_dist[float32-libertem-native]                    96.5851 (1.0)        104.7064 (1.0)         99.5392 (1.0)       2.7379 (10.44)       98.4527 (1.0)       4.3432 (13.28)         3;0  10.0463 (1.0)          11           1
test_concurrent[float32-libertem-native]             105.6957 (1.09)       109.4521 (1.05)       107.8878 (1.08)      1.3417 (5.12)       107.9306 (1.10)      2.0206 (6.18)          3;0   9.2689 (0.92)         10           1
test_dist[uint16-libertem-native]                    188.7214 (1.95)       193.5124 (1.85)       191.5004 (1.92)      1.6443 (6.27)       191.6184 (1.95)      1.7767 (5.43)          2;0   5.2219 (0.52)          6           1
test_concurrent[uint16-dask.array-delayed]           268.5256 (2.78)       343.9102 (3.28)       289.4308 (2.91)     31.4886 (120.11)     276.2080 (2.81)     33.0430 (101.02)        1;0   3.4551 (0.34)          5           1
test_concurrent[float32-dask.array-delayed]          277.1342 (2.87)       353.8087 (3.38)       294.3009 (2.96)     33.4187 (127.48)     278.0926 (2.82)     24.7009 (75.52)         1;1   3.3979 (0.34)          5           1
test_inline[float32-mmap-native]                     291.3631 (3.02)       292.0523 (2.79)       291.6401 (2.93)      0.2622 (1.0)        291.6184 (2.96)      0.3271 (1.0)           2;0   3.4289 (0.34)          5           1
test_dist[uint16-libertem-delayed]                   314.1723 (3.25)       378.0796 (3.61)       361.3303 (3.63)     26.7474 (102.03)     372.4488 (3.78)     23.2945 (71.22)         1;1   2.7676 (0.28)          5           1
test_dist[float32-libertem-delayed]                  332.7703 (3.45)       353.8066 (3.38)       343.7033 (3.45)      8.7899 (33.53)      344.8987 (3.50)     15.0923 (46.14)         2;0   2.9095 (0.29)          5           1
test_dist[uint16-dask.array-delayed]                 379.7147 (3.93)       500.6664 (4.78)       417.8195 (4.20)     48.2270 (183.96)     396.1229 (4.02)     47.0591 (143.88)        1;0   2.3934 (0.24)          5           1
test_concurrent[float32-libertem-delayed]            380.2372 (3.94)       480.8705 (4.59)       409.6345 (4.12)     40.6699 (155.14)     394.5492 (4.01)     35.3298 (108.01)        1;1   2.4412 (0.24)          5           1
test_dist[float32-dask.array-delayed]                399.9328 (4.14)       532.7104 (5.09)       440.1395 (4.42)     57.0847 (217.75)     407.2610 (4.14)     75.3263 (230.30)        1;0   2.2720 (0.23)          5           1
test_inline[float32-libertem-native]                 428.9905 (4.44)       431.2598 (4.12)       429.7690 (4.32)      0.8992 (3.43)       429.5905 (4.36)      1.0776 (3.29)          1;0   2.3268 (0.23)          5           1
test_concurrent[uint16-libertem-native]              603.2058 (6.25)       642.0634 (6.13)       618.7185 (6.22)     16.3244 (62.27)      618.4665 (6.28)     26.5358 (81.13)         1;0   1.6162 (0.16)          5           1
test_inline[uint16-mmap-native]                      628.5914 (6.51)       630.5247 (6.02)       629.5929 (6.33)      0.9187 (3.50)       630.0043 (6.40)      1.6820 (5.14)          3;0   1.5883 (0.16)          5           1
test_concurrent[uint16-dask.array-from_array]        689.7179 (7.14)       754.0496 (7.20)       718.8046 (7.22)     23.9671 (91.42)      715.5608 (7.27)     30.8816 (94.41)         2;0   1.3912 (0.14)          5           1
test_concurrent[float32-dask.array-from_array]       844.2303 (8.74)       937.7819 (8.96)       876.7817 (8.81)     37.4544 (142.87)     868.8421 (8.82)     48.4283 (148.06)        1;0   1.1405 (0.11)          5           1
test_concurrent[float32-libertem-from_array]         844.5235 (8.74)       902.4180 (8.62)       883.4101 (8.87)     22.4810 (85.76)      889.4376 (9.03)     18.6970 (57.16)         1;1   1.1320 (0.11)          5           1
test_concurrent[uint16-libertem-delayed]             896.2479 (9.28)       926.5397 (8.85)       909.7663 (9.14)     14.0868 (53.73)      902.7809 (9.17)     25.1269 (76.82)         1;0   1.0992 (0.11)          5           1
test_inline[uint16-libertem-native]                1,124.4429 (11.64)    1,143.6032 (10.92)    1,136.6703 (11.42)     7.4138 (28.28)    1,139.1677 (11.57)     8.4849 (25.94)         1;0   0.8798 (0.09)          5           1
test_concurrent[uint16-libertem-from_array]        1,127.6862 (11.68)    1,162.0742 (11.10)    1,145.0594 (11.50)    15.6803 (59.81)    1,144.7598 (11.63)    29.5928 (90.47)         2;0   0.8733 (0.09)          5           1
test_inline[float32-libertem-delayed]              1,497.3403 (15.50)    1,504.1318 (14.37)    1,500.8737 (15.08)     2.4262 (9.25)     1,501.0989 (15.25)     2.3634 (7.23)          2;0   0.6663 (0.07)          5           1
test_inline[float32-libertem-from_array]           1,588.5484 (16.45)    1,646.2888 (15.72)    1,621.8148 (16.29)    23.3394 (89.03)    1,626.9948 (16.53)    36.6815 (112.15)        2;0   0.6166 (0.06)          5           1
test_inline[uint16-libertem-from_array]            1,738.8045 (18.00)    1,807.2875 (17.26)    1,758.0760 (17.66)    28.0280 (106.91)   1,748.6638 (17.76)    24.6070 (75.23)         1;1   0.5688 (0.06)          5           1
test_inline[uint16-libertem-delayed]               1,876.3366 (19.43)    1,900.8304 (18.15)    1,885.8756 (18.95)    10.3656 (39.54)    1,883.0895 (19.13)    16.9360 (51.78)         1;0   0.5303 (0.05)          5           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
================================================================================== short test summary info ===================================================================================
FAILED benchmarks/io/test_dask.py::TestDaskArray::test_dist[uint16-libertem-from_array] - concurrent.futures._base.CancelledError: check_valid-ab325c8e-4b7b-4d58-ae00-22a429f1afdc
FAILED benchmarks/io/test_dask.py::TestDaskArray::test_dist[uint16-dask.array-from_array] - concurrent.futures._base.CancelledError: check_valid-4f1b4973-d53b-423c-9488-57742aca4452
FAILED benchmarks/io/test_dask.py::TestDaskArray::test_dist[float32-libertem-from_array] - concurrent.futures._base.CancelledError: check_valid-68cacf66-a27f-4383-b57f-19379068ac55
FAILED benchmarks/io/test_dask.py::TestDaskArray::test_dist[float32-dask.array-from_array] - concurrent.futures._base.CancelledError: check_valid-be1603fa-2f9b-449a-99a5-940919523c36
============================================================== 4 failed, 24 passed, 8 skipped, 4 warnings in 262.76s (0:04:22) ===============================================================
```

## What the tags mean

test_dist[...] : Distributed multi-process Dask cluster, including for native Dask operations

test_inline[...]: InlineJobExecutor, default threaded Dask executor

test_concurrent[...]: ConcurrentJobExecutor, default threaded Dask executor

...[{float32,uint16}, ...]: dtype of the raw file. The number of pixels is constant, meaning the float32 file is twice as large. In LiberTEM this will be processed along a different code path: `float32` will be passed through as very large single memory-mapped tile by default, while `uint16` will be converted to `float32` in small tiles of 1 MB for improved cache efficiency.

...[...,  libertem, ...]: Benchmark using a LiberTEM executor and UDF
...[...,  dask.array, ...]: Benchmark using Dask array methods as a baseline
...[...,  mmap, ...]: Benchmark using NumPy on a memory map of the whole file as a baseline

...[..., ..., native]: Benchmark a native RAW LiberTEM dataset as a baseline
...[..., ..., delayed]: Benchmark a "properly" created Dask array based on a composition of dask.delayed memory-mapped chunks.
...[..., ..., from_array]: Benchmark a "quick and dirty" Dask array created with `da.from_array(np.memmap(...))`.


## Results

The `ConcurrentJobExecutor` works very well on large tiles (float32 case). On small tiles (uint16) it is a lot slower than the multi-process executor. Native LiberTEM with multiprocess executor is fast for both float32 and uint16.

da.from_array(np.memmap(...))` is incompatible with process-based executors. Here it fails outright with both LiberTEM and native Dask operations because the resulting Task objects are above a size limit. Likely it triggers sending the entire file through the cluster. 

The `delayed` Dask arrays generally perform better than `from_array`, meaning the chunking scheme we chose is good for this use case. Native Dask array operations do pretty well with both threaded and distributed Dask executors if the array is created appropriately.

Operations on Dask arrays using LiberTEM are a mixed bag. A "good" Dask array on the distributed executor does pretty well --` test_dist[float32-libertem-delayed]` and `test_dist[uint16-libertem-delayed]` are by and large competitive with native Dask array operations. Operations using the `ConcurrentJobExecutor` are not as good, but still better than `InlineJobExecutor`.

The `InlineJobExecutor` is performing rather poorly in the tests, including native `uint16` processing in comparison to the `mmap` baseline and other executors. The machine has a very high memory bandwidth, large memory and large CPU caches, which means improved cache efficiency will not matter much for a single thread and processing in small tiles seems to create too much overheads.

## Conclusion

Discussion with @sk1p: The `ConcurrentJobExecutor` is likely slowed down by the Python GIL, since the `float32` case processes an entire partition with released GIL on par with a multiprocess executor, while the `uint16` case works in many small units where multiprocessing is a lot faster.

`ConcurrentJobExecutor` does meet the endpoint of running reasonably well on "quick and dirty" Dask arrays where it is significantly faster than `InlineJobExecutor`. Possibly things can still be improved by using the same thread pool as Dask?

Discussion with @sk1p: We'd like to include the `ConcurrentJobExecutor` as a test case and option to fix issues with Dask integration. It can be a good benchmark for parameter transfer as long as whole partitions are processed.

On the Hyperspy integration side it turns out that some file types are read "properly" using `delayed`, while others effectively use `from_array()`. Possibly we can help fix Hyperspy readers to be generally compatible with a distributed Dask executor, which means they will also work well with the LiberTEM `DaskJobExecutor`.

**Comment by matbryan52** [comment]
Having a look at the following remark:

>Possibly things can still be improved by using the same thread pool as Dask?

In the benign case I believe that Dask creates its default `ThreadPoolExecutor` in the following file: [threaded.py](https://github.com/dask/dask/blob/main/dask/threaded.py) if the scheduler has been set to 'threads' either via a config or in the compute call kwargs. The `default_pool` object can be imported from this file, and if it has been created yet then it will work for the `ConcurrentJobExecutor`. 

In the case it has not been created, we either have to check the `pools` dict in that file, which is filled with pools either from workers or if `max_workers` has been set, or create our own pool (and possibly monkey-patch it as the `default_pool`).

It should also be possible to have multiple `ThreadPoolExecutor` references held by `ConcurrentJobExecutor`, based on the available pools, and use the one which is most appropriate to the worker thread (or create one ourselves if it doesn't exist yet).

It's all a bit dangerous, though, as I don't think Dask consider this to be a public endpoint!

**Comment by uellue** [comment]
Superseded by #1170

**Pull request closed without merging**
