### PR TITLE
Documentation for Radial Fourier Analysis based on PR #362

### PR DESCRIPTION
**Pull request by uellue**
Figures and sample script

Based on PR #362!

### CODE REVIEW

**Comment by sk1p** [comment]
Can you please rebase onto current master? Thanks!

**Comment by uellue** [comment]
> Can you please rebase onto current master? Thanks!

Done! :-)

**Comment by sk1p** [comment]
Offline discussion: the long list of images is not optimal; one thing we can try is to directly integrate an ipython notebook into the documentation and have the plots inline.

**Comment by sk1p** [comment]
Contributing docs, "Building the Documentation", needs a link to https://pandoc.org/installing.html. Can you also clean up regarding unused files? Or do we still need the `*_order_*.svg` files?

**Comment by uellue** [comment]
@sk1p the pandoc installation and the unused files should be addressed now.

**Comment by sk1p** [comment]
Looks good, merging!

**Pull request merged**
