### PR TITLE
Fix "RuntimeError: no running event loop" at `libertem-server` startup

### PR DESCRIPTION
**Pull request by sk1p**
Fix for the following exception at startup:

```
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Line:     return _run_code(code, main_globals, None,
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/runpy.py", line 87, in _run_code
Line:     exec(code, run_globals)
Line:   File "/home/alex/source/LiberTEM/src/libertem/web/cli.py", line 109, in <module>
Line:     main()
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
Line:     return self.main(*args, **kwargs)
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/site-packages/click/core.py", line 1055, in main
Line:     rv = self.invoke(ctx)
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Line:     return ctx.invoke(self.callback, **ctx.params)
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/site-packages/click/core.py", line 760, in invoke
Line:     return __callback(*args, **kwargs)
Line:   File "/home/alex/source/LiberTEM/src/libertem/web/cli.py", line 99, in main
Line:     run(
Line:   File "/home/alex/source/LiberTEM/src/libertem/web/server.py", line 225, in run
Line:     executor_state = ExecutorState(snooze_timeout=snooze_timeout)
Line:   File "/home/alex/source/LiberTEM/src/libertem/web/state.py", line 54, in __init__
Line:     self._loop = asyncio.get_running_loop()
Line: RuntimeError: no running event loop
```

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code from MIT code

### CODE REVIEW

**Review by matbryan52 — CHANGES_REQUESTED** [review]
I like the test case!

That said I have a failure on Windows / Python 3.11 :

```python
================================================================ FAILURES =================================================================
____________________________________________________ test_libertem_server_cli_startup _____________________________________________________

    @pytest.mark.asyncio
    async def test_libertem_server_cli_startup():
        # make sure we can start `libertem-server` and stop it again using ctrl+c
        # this is kind of a smoke test, which should cover the main cli functions.
>       p = await asyncio.create_subprocess_exec(
            sys.executable, '-m', 'libertem.web.cli', '--no-browser',
            stderr=asyncio.subprocess.PIPE,
        )

tests\server\test_startup.py:285:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\envs\lt_fork\Lib\asyncio\subprocess.py:221: in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
..\..\envs\lt_fork\Lib\asyncio\base_events.py:1694: in subprocess_exec
    transport = await self._make_subprocess_transport(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_WindowsSelectorEventLoop running=False closed=False debug=False>, protocol = <SubprocessStreamProtocol>
args = ('D:\\mb265392\\envs\\lt_fork\\python.exe', '-m', 'libertem.web.cli', '--no-browser'), shell = False, stdin = None, stdout = None
stderr = -1, bufsize = 0, extra = None, kwargs = {}

    async def _make_subprocess_transport(self, protocol, args, shell,
                                         stdin, stdout, stderr, bufsize,
                                         extra=None, **kwargs):
        """Create subprocess transport."""
>       raise NotImplementedError
E       NotImplementedError
```

**Comment by sk1p** [comment]
Thanks for having a look!

> That said I have a failure on Windows / Python 3.11 :

[...]

> ```
> self = <_WindowsSelectorEventLoop running=False closed=False debug=False>, protocol = <SubprocessStreamProtocol>
> args = ('D:\\mb265392\\envs\\lt_fork\\python.exe', '-m', 'libertem.web.cli', '--no-browser'), shell = False, stdin = None, stdout = None
> stderr = -1, bufsize = 0, extra = None, kwargs = {}
> 
>     async def _make_subprocess_transport(self, protocol, args, shell,
>                                          stdin, stdout, stderr, bufsize,
>                                          extra=None, **kwargs):
>         """Create subprocess transport."""
> >       raise NotImplementedError
> E       NotImplementedError
> ```

Oof yeah, Windows needs a `ProactorEventLoop` to work with subprocesses in `asyncio`, which doesn't play well with tornado IIRC. 

I'm using `asyncio` here because I want to read from the pipe with a timeout, which is not possible in vanilla `subprocess` without going to platform-specific `poll`ing or similar.

I'll see if we can influence the event loop policy for this specific test case somehow. 

> Invoked with `pytest -m 'web_api' .\tests\server\test_startup.py`, which might be incorrect...

That looks correct.

**Comment by sk1p** [comment]
I've now put the test into its own module to be able to specify the correct event loop policy, and also added a ton of windows-specific workarounds. It's also no longer part of the `web_api` mark, so it'll run on a broader range of platforms and Python versions. Hopefully it's not too slow and flaky in CI...

**Review by matbryan52 — APPROVED** [review]
The changes have worked on one system. On another system I have a `TimeoutError` when awaiting the first call to `readline()` with the 5 second delay. This is probably just my system.

It also passes in normal CI so I think it's fine to go!

**Comment by sk1p** [comment]
> The changes have worked on one system. On another system I have a `TimeoutError` when awaiting the first call to `readline()` with the 5 second delay. This is probably just my system.

Oof, yeah, we could think about increasing that timeout, maybe even substantially. If you continue to hit this, feel free to change!

> It also passes in normal CI so I think it's fine to go!

:+1:

**Pull request merged**
