### PR TITLE
Try harder to cancel the progress bar on cancellation

### LINKED ISSUE #1548: Progress bar doesn't reset when dataset is closed with task in flight
## How to reproduce

* Open a dataset and start an analysis with non-trivial runtime.
* Close the dataset while processing is still going on and the progress bar is shown.
* Open the dataset again and process again.

## What happens

* The progress bar gets stuck at the point where the dataset was closed.
* The progress bar moves forward with the new processing, but then resets to the previous state once the new processing finishes.

## What should happen

The pending tasks from a dataset are removed from the progress bar when a dataset is closed.

### PR DESCRIPTION
**Pull request by sk1p**
It can happen that a progress report comes in after a job has been successfully cancelled - so we can't rely on removing the progress state only on finishing events, we need to listen to the explicit 'end' progress hook.

This updates the web API to emit specific progress events.

Fixes #1548

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by sk1p** [comment]
docs-check failure is the numpy intersphinx failing once again...

**Comment by uellue** [comment]
Thx, fix confirmed, merging!

**Pull request merged**
