### PR TITLE
Make sure live plots work with the widget backend

### PR DESCRIPTION
**Pull request by uellue**
The newest versions of jupyterlab and notebook don't support the `nbagg` backend anymore. Instead the `widget` backend is supposed to be used: https://matplotlib.org/stable/users/explain/figure/interactive.html#jupyter-notebooks-jupyterlab

With this change the `widget` backend shows and updates the plots live as it is supposed to. It also uses the recommended live drawing functions for matplotlib:
https://matplotlib.org/stable/users/explain/figure/interactive_guide.html#explicitly-spinning-the-event-loop

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code from MIT code

### CODE REVIEW

**Comment by uellue** [comment]
CC @sivborg!

**Comment by uellue** [comment]
Hm, why are the data test failing now? The notebook test that failed previously seems successful.

**Comment by uellue** [comment]
Something is not quite right in CI, it seems, Suddenly there are errors after errors.

**Comment by uellue** [comment]
The HyperSpy issue is not reproduced locally on Python 3.11, Windows

**Review by sk1p — APPROVED** [review]
LGTM! Tested on both `notebook~=6` and `notebook>=7` with the live plotting notebook, seems to work fine (though the processing with that data set is too fast to actually see intermediate results and to be able to judge how interactive things are etc. - I think this is something we'll only find out in real usage).

**Pull request merged**
