### PR TITLE
Fix standard deviation for complex input data

### PR DESCRIPTION
**Pull request by uellue**
* A few absolute values were missing

Fortunately this is an edge case since we hardly process any complex input data!

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by uellue** [comment]
@sk1p test failure in notebooks was due to [OSError: [Errno 28] No space left on device](https://dev.azure.com/LiberTEM/LiberTEM/_build/results?buildId=1932&view=logs&j=4d6f0f97-9d62-53bc-79d2-96c85fc226be&t=b5ec37f2-4755-55f4-9304-bcf3d588aca8&l=370). On Moellenstedt it looks normal, how are your agents?

**Comment by uellue** [comment]
I'm re-running the notebook tests, let's see!

**Comment by sk1p** [comment]
Running the fuzz test gives:

```
  /home/alex/source/LiberTEM/src/libertem/udf/stddev.py:358: ComplexWarning: Casting complex values to real discards the imaginary part
    self.results.varsum[:] = np.var(tile, axis=0, ddof=n_1 - 1, dtype=dtype)
```

Possible bug?

**Comment by uellue** [comment]
> Possible bug?

A "wart" since variance is always non-negative real, but better to avoid the unsafe cast and make it explicit!

**Pull request merged**
