### PR TITLE
Fix CoM result download

### PR DESCRIPTION
**Pull request by sk1p**
- Allow `AnalysisResult` to be tagged with `include_in_download=False`
 - When downloading, filter `AnalysisResultSet` to only include results that should be
   downloaded
 - Fix `AnalysisResult.__array__` to always coerce the raw data to np.ndarray

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases

### CODE REVIEW

**Comment by uellue** [comment]
Looking good, confirmed to fix the bug on my system.

When looking at the data, I noticed that we need some sort of indication which layers or components are omitted from the result set. Before, there was an 1:1 matching between items in the drop-down and layers in the result. At least in Fiji I can't see any indication which layer is which.

Perhaps a zip file with individual files for each layer as discussed in #665 and a JSON file with metadata would be better? Maybe being able to encode all information to completely restore an `AnalysisResultSet` could be a good guiding principle for designing the download format?

**Comment by sk1p** [comment]
> When looking at the data, I noticed that we need some sort of indication which layers or components are omitted from the result set. Before, there was an 1:1 matching between items in the drop-down and layers in the result. At least in Fiji I can't see any indication which layer is which.

True.

> Perhaps a zip file with individual files for each layer as discussed in #665 and a JSON file with metadata would be better? 

I don't think it would be strictly better - a TIFF file you can directly open in DM/Fiji/GIMP/... - zipped, you first need to fiddle around with file management.  I would agree that it would be nice to have a zip w/ layers + parameters.json download format in addition.

Sadly, TIFF doesn't support layer names, or this would be a no-brainer... HDF5 is much better suited for this kind of application, IMHO:

```
In [2]: f = h5py.File("/home/alex/Downloads/results.h5", "r")                   

In [3]: f.keys()                                                                
Out[3]: <KeysViewHDF5 ['divergence', 'magnitude', 'x', 'y']>
```

> Maybe being able to encode all information to completely restore an `AnalysisResultSet` could be a good guiding principle for designing the download format?

Yeah, see #687 - we should write analysis and dataset parameters into formats that support those.

**Comment by sk1p** [comment]
> Perhaps indicating in the GUI layer drop-down or in the result download dialogue which layers are included in download?

Sounds good. Could be done by serializing the "included with download" flag together with the result set, and querying that from the download modal.

**Comment by sk1p** [comment]
image

**Comment by sk1p** [comment]
This is now implemented, let me know if this works for you. Should be merge-able after rebuilding the client, feel free to take over the PR tomorrow.

**Comment by uellue** [comment]
Fix confirmed, many thanks! :-)

**Pull request merged**
