### PR TITLE
Use thread control for Numba

### PR DESCRIPTION
**Pull request by uellue**
Refs https://github.com/LiberTEM/LiberTEM/pull/685#issuecomment-625939720

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

### CODE REVIEW

**Comment by uellue** [comment]
imagecodecs seems to have an installation problem, tripping the Travis run 🙄

**Comment by sk1p** [comment]
> imagecodecs seems to have an installation problem, tripping the Travis run

That's weird. It looks like the pip used by tox doesn't like the manylinux2010 and manylinux2014 wheels that are published for imagecodecs. It looks like it may be caused by a change of the travis environment, as the last release of imagecodecs was Feb 18...

**Comment by sk1p** [comment]
Yeah, other binaries are installed with the `manylinux1` tag - that should only happen if `pip` is older than `19`. Let me quickly push something to see if updating virtualenv helps

**Comment by sk1p** [comment]
Looks like that helped!

**Pull request merged**
