### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by sk1p**
TODO:

- [x] port release infra to azure (`TRAVIS_*` env vars in `scripts/release`, replace `travis-sphinx` in `docs-deploy` w/ something else)
- [x] add windows and mac os to testing matrix
- [x] add docker-compose based tests
- [x] Fix Python 3.8 tests on Windows

Maybe postpone these to later:

- [ ] finish setting up local Agent for tests w/ dataset access
- [ ] add "release" information (continuous, rc, stable release; which version? etc.) as environment variables to all ci steps, and make it available as environment variables for running tests. could be (ab)used to xfail/skip known flaky tests
- [ ] Add packaging secrets as variables, making sure they are only available in the right context

### CODE REVIEW

**Comment by sk1p** [comment]
Something I came across while patching up the pipeline: there is a [azure pipelines template project](https://github.com/tox-dev/azure-pipelines-template) which makes some tox-related templates available. For me, this was a bit complicated for getting started with azure+tox, but maybe something to keep in mind for the future

**Comment by sk1p** [comment]
Another useful link, for implementing a "cross-product"-like testing matrix by templating: https://github.com/microsoft/azure-pipelines-yaml/issues/20#issuecomment-491349961

**Comment by uellue** [comment]
Including in 0.6 milestone since organization page and Python 3.8 tests depend on this.

**Comment by sk1p** [comment]
This now [hit a race condition](https://dev.azure.com/LiberTEM/LiberTEM/_build/results?buildId=14&view=logs&j=9d73d1fc-3a9e-5ba7-6ad9-e21fc4cd7ca4&t=166bcb7a-b1a3-550e-b07c-c68401b8ea86) (https://github.com/dask/distributed/issues/3969) which should be fixed in the next distributed version

**Comment by uellue** [comment]
Discussion with @sk1p: Bump priority since travis-ci will limit access for open source projects: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Review by uellue — APPROVED** [review]
That all looks pretty green and sensible to me. :-) Nice to have all the OSes in one CI configuration! I'll merge this now, and we'll test the release process with 0.6 to make sure all env vars are set correctly etc. Thx for dealing with all this!

**Comment by uellue** [comment]
I've squashed it since it had a number of trial-and-error commits in there, as it happens when dealing with CI. :-)

**Comment by sk1p** [comment]
> That all looks pretty green and sensible to me. :-) Nice to have all the OSes in one CI configuration! I'll merge this now, and we'll test the release process with 0.6 to make sure all env vars are set correctly etc. Thx for dealing with all this!

Thanks for the review! Btw. I could reproduce the failures related to event loop policy on Python 3.8 w/ Windows on my Laptop - is your environment still on Python 3.7? 

> I've squashed it since it had a number of trial-and-error commits in there, as it happens when dealing with CI. :-)

Yeah, good call.

It looks like the master branch didn't get built after merging this PR - I'm not sure why this is the case. The pipeline definition itself is set to trigger on the `master` branch, and because of the default settings, all PRs will also be built. The triggers setting also shows that continuous integration is enabled:

image

Maybe something needs to be changed on the GitHub side too, I'll have a look.

**Comment by uellue** [comment]
Unfortunately it seems that Azure is quite buggy: https://developercommunity.visualstudio.com/content/problem/1272448/not-possible-to-join-an-organization-after-invitat.html We should be on the lookout for a better solution.

**Pull request merged**
