### PR TITLE
Large UDF parameters on large files overrun worker memory

### PR DESCRIPTION
**Pull request by uellue**
The included notebook triggers excessive memory use on Dask workers.
The size of UDF parameters seems to be the reason.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [N/A] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
Is this now "fixed" by #1143? It should now work properly given that memory in the order of `n_workers*sizeof(A)` is available, right?

**Comment by uellue** [comment]
Fix confirmed in current master! :rocket:

**Comment by uellue** [comment]
The dist case is now actually faster than the inline one, impressive!

**Comment by uellue** [comment]
...and this use case is also tested in the benchmarks for #1143, so no need for this reproducer anymore. :-)

**Pull request closed without merging**
