### PR TITLE
Implement preloading for server and worker

### PR DESCRIPTION
**Pull request by uellue**
Essential to load HDF5 with custom filters. See https://libertem.github.io/LiberTEM/reference/dataset.html#hdf5

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by uellue** [comment]
Adding priority since the feature was in our documentation, but not implemented.

**Comment by uellue** [comment]
@sk1p I'm not so sure if I implemented passing the parameter to the web server correctly. Could you have a look please? :-)

**Review by sk1p — CHANGES_REQUESTED** [review]
>  I'm not so sure if I implemented passing the parameter to the web server correctly. Could you have a look please? :-)

It should work like this! An alternative would be to put `preload` into `SharedState`, like `local_directory`, then we don't need to pass it down individually (this is especially important when we start to add more "stuff" that needs to be passed down...)

**Comment by uellue** [comment]
Thx @sk1p! :-) Should be ready now.

**Review by sk1p — APPROVED** [review]
LGTM!

**Pull request merged**
