### PR TITLE
documentation for get_diagnostics()

### PR DESCRIPTION
**Pull request by sayandip18**
This is for #258 and #637 

## Contributor Checklist:

* [ ] I have added myself to [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

### CODE REVIEW

**Comment by sayandip18** [comment]
Is there anything that needs to be added to the already existing [documentation](https://libertem.github.io/LiberTEM/reference/dataset.html#libertem.io.dataset.base.DataSet.get_diagnostics) for `get_diagnostics` or is it enough?

**Comment by uellue** [comment]
> Is there anything that needs to be added to the already existing documentation for get_diagnostics or is it enough?

The documentation for the base class is enough IMO. You could document what information the `get_diagnostics()` methods in each subclass return.

Are the changes in `win_tweaks.py` intentionally in this PR or just included by accident?

**Comment by sayandip18** [comment]
> The documentation for the base class is enough IMO. You could document what information the `get_diagnostics()` methods in each subclass return.

Ok, will include them too.

> Are the changes in `win_tweaks.py` intentionally in this PR or just included by accident?

Intentional. Also, intend to include tests for examples notebooks (#595) and profiling techniques (#589) in this too. I will change the name of the PR to something more general once I figure it out.

**Comment by uellue** [comment]
> Intentional. Also, intend to include tests for examples notebooks (#595) and profiling techniques (#589) in this too. I will change the name of the PR to something more general once I figure it out.

Keeping unrelated changes in separate pull requests works better. That way they can be reviewed and merged separately. You can keep them in separate branches. In my workflow I keep the master branch of my fork in sync with the upstream master and make all my modifications in branches. That makes it easy to always create new branches starting from the current upstream master, and rebase branches on the current master when necessary.

What about first finishing with #258 before tacking more issues? Did you reproduce the error described in the issue and confirm that your change fixes it? On my system it still happens with Git for Windows Bash when I run your version.

**Comment by sayandip18** [comment]
> What about first finishing with #258 before tackling more issues?

Okay, will do that

> Did you reproduce the error described in the issue and confirm that your change fixes it? 

No, I haven't. I had no idea that it could be done that way. How do you do it?

**Comment by uellue** [comment]
> How do you do it?

With Git for Windows Bash instead of cmd.exe, for example. 🤷

**Comment by sayandip18** [comment]
> With Git for Windows Bash instead of cmd.exe, for example. 🤷

Yeah, but that runs the [master branch](https://github.com/LiberTEM/LiberTEM). How do I run [my version](https://github.com/sayandip18/LiberTEM) which has all the commits that I have made?

**Comment by sk1p** [comment]
> How do I run [my version](https://github.com/sayandip18/LiberTEM) which has all the commits that I have made?

Please see [the installation documentation](https://libertem.github.io/LiberTEM/install.html#installing-from-a-git-clone) - adjust the steps accordingly, if you already have a clone of your fork on your computer. Let me know if this works for you.

**Comment by sayandip18** [comment]
Made a few mistakes, cannot even delete the previous commits. Closing this. Will open a new PR.

**Pull request closed without merging**
