### PR TITLE
MIB: fix and document `disable_glob` parameter

### PR DESCRIPTION
**Pull request by sk1p**
## Contributor Checklist:

* [N/A] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
Thinking about this a bit, we could also implement a heuristic that automatically disables globbing (based on the sequence numbers in the .mib files), but that could be a bit surprising behavior. On the other hand, it would also work from the GUI, where it currently fails with an obscure error...

**Comment by uellue** [comment]
Probably better to add a GUI element that allows to enable or disable globbing? The heuristic could be used to set the starting value. As you write, the behavior could be really surprising depending on how people name and organize their files. With the GUI element it would be transparent that there are two modes available, and people can influence the behavior.

**Comment by sk1p** [comment]
> Probably better to add a GUI element that allows to enable or disable globbing? The heuristic could be used to set the starting value. As you write, the behavior could be really surprising depending on how people name and organize their files. With the GUI element it would be transparent that there are two modes available, and people can influence the behavior.

I think this would go hand-in-hand with general support for specifying stacks of files in the GUI, for cases where no default naming scheme exists (MIB, TVIPS, FRMS6, K2IS, maybe others all have a usable default naming scheme, but if you have a stack of raw files, or a stack of DM3, things will be different...) - basically #498

**Comment by uellue** [comment]
Discussion with @sk1p: We defer a "proper" solution for #498 to later and merge this now as-is. :-) Thx for taking care of it!

**Pull request merged**
