### PR TITLE
Remove compatibility code

### PR DESCRIPTION
**Pull request by uellue**
Follow https://github.com/numpy/numpy/blob/main/numpy/lib/format.py where this code was copied from.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [x] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by uellue** [comment]
Looking at https://github.com/numpy/numpy/blob/main/numpy/lib/format.py, we won't get away so easily. The array format changed with NumPy 2.0, so this will be a bigger project to make sure we support old and new .npy.

**Comment by matbryan52** [comment]
> Looking at https://github.com/numpy/numpy/blob/main/numpy/lib/format.py, we won't get away so easily. The array format changed with NumPy 2.0, so this will be a bigger project to make sure we support old and new .npy.

Will hopefully not take too long to do, and I would imagine we won't encounter newer format files often. I get the impression they are using the older format whenever possible for compatibility and only using the newer for unicode header names or many column structures.

**Comment by uellue** [comment]
> > Looking at https://github.com/numpy/numpy/blob/main/numpy/lib/format.py, we won't get away so easily. The array format changed with NumPy 2.0, so this will be a bigger project to make sure we support old and new .npy.
> 
> Will hopefully not take too long to do, and I would imagine we won't encounter newer format files often. I get the impression they are using the older format whenever possible for compatibility and only using the newer for unicode header names or many column structures.

Ah, good to know! Thinking about it, since we are creating .npy files with NumPy 2 in the tests, we should be more or less fine as long as they pass.

**Comment by uellue** [comment]
Instead of copying the functions, perhaps we can memory map the file, get the parameters and immediately close the memory map? I'd expect/hope that memory mapping is a noop until actually accessing the memory region.

**Review by sk1p — APPROVED** [review]
LGTM! I didn't see the new npy file format though - as far as I can see, format 3.0 is the latest and was added in numpy 1.17:

https://github.com/numpy/numpy/blob/594657d38b12b1fdc7f620ed026c8df93f271cb3/numpy/lib/format.py#L426-L429

Anyway, using `open_memmap`, we should be be as compatible as we can.

**Pull request merged**
