### PR TITLE
Better random data with guaranteed asymmetry; numerical test

### LINKED ISSUE #225: More stringent mathematical tests
Right now, the tests do cover the basics regarding mathematical correctness. However, two items should be addressed:

- [ ] We should test for numerical errors and instabilities, for example sums of many very small numbers or sums of values with a high dynamic range, similar to our input data.
- [ ] We should make sure that our test data has "good randomness", i.e. strong asymmetries and value spread. Right now, arrays are usually populated with `np.random.choice(a=[0, 1], ...)` and results are checked with `np.allclose(..)`. That could miss errors like flipped dimensions, mixed up partitions etc. because errors would average out if the data sets are large enough.

### PR DESCRIPTION
**Pull request by uellue**
Closes #225

### CODE REVIEW

**Comment by sk1p** [comment]
Failing testcase seems to be caused by missing import of `_mk_random` in the local cluster tests.

**Comment by uellue** [comment]
WIP because I'll try sth about the numerical precision as well.

**Comment by sk1p** [comment]
On the topic of numerical stability (for `np.sum`, similar problems may apply to OpenBLAS): https://github.com/numpy/numpy/issues/8786

**Comment by uellue** [comment]
Closes #225

**Comment by sk1p** [comment]
Thanks, looks good! Btw. I don't think "closes" etc. works as comment, edited this into the description of the PR.

**Pull request merged**
