### PR TITLE
WIP: Add support for python script

### PR DESCRIPTION
**Pull request by twentyse7en**
Generate python script corresponding to analysis.
User can select between notebook and python file
to download in GUI.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if
changes were made to the GUI)

### CODE REVIEW

**Review by sk1p — COMMENTED** [review]
Hey, I've added some initial feedback, hope this helps!

**Comment by twentyse7en** [comment]
In the python script, should we plot the result or just run the analysis?

**Comment by sk1p** [comment]
> In the python script, should we plot the result or just run the analysis?

I would say include the plotting - it's easier to remove the plotting part from the generated code than the other way around, and it is an example of how to access the results of the analysis.

For testing, it should be possible to configure a non-interactive matplotlib backend, for example one that saves as PNG.

**Comment by uellue** [comment]
Hi @twentyse7en, this looks good! A few ideas for possible improvements:

- [ ] At least for Ring Analysis, the sum UDF is run without progress bar, while the analysis has it activated. Having both with progress would be better. Could you perhaps check the code if there are more instances without progress bar?
- [ ] A `plt.show()` at the end of the script makes it actually do something visible for the user. :-)
- [ ] Since a plain script misses all context from the code that is being run, it would be important to print which analysis or UDF is being run and to set the plot title. Example: `print("Running SumUDF...")` and `plt.title("SumUDF")`. If it helps to write less code, one can get the class name like this: `type(sum_udf).__name__`
- [ ] The generated code rings up a number of flake8 errors. Those can be fixed automatically with `autoflake` and `black`, which is probably easier and more comprehensive than fixing the generating code. :-)

**Comment by uellue** [comment]
> * The generated code rings up a number of flake8 errors. Those can be fixed automatically with `autoflake` and `black`, which is probably easier and more comprehensive than fixing the generating code. :-)

... or use autopep8, since LiberTEM already depends on that.

**Comment by sk1p** [comment]
@twentyse7en let me know if you need any additional feedback/code review on this!

**Comment by twentyse7en** [comment]
> @twentyse7en let me know if you need any additional feedback/code review on this!

I will look into this immediately after finishing #885, sorry for the delay.

**Comment by twentyse7en** [comment]
>     * Example: `print("Running SumUDF...")` and `plt.title("SumUDF")`. If it helps to write less code, one can get the class name like this: `type(sum_udf).__name__`

Currently it prints `running sum analysis`. Or should we go with type name as mentioned above @uellue.

Also there is a issue with the client, when I tried running the client it just keep spinning.

**Comment by sk1p** [comment]
> Currently it prints `running sum analysis`. 

Sounds good to me :+1:

> Also there is a issue with the client, when I tried running the client it just keep spinning.

Are there any errors? Either via command line output, or in the browser's console? At what status is it spinning, at "connecting"? Any more details?

**Comment by twentyse7en** [comment]
<summary>
On the server, this message is being repeated
<details>
```
[2020-11-27 21:50:34,328] INFO [libertem.web.base.log_message:23] message: CONFIG
[2020-11-27 21:50:35,415] INFO [libertem.web.connect.get:22] ConnectHandler.get
[2020-11-27 21:50:35,421] INFO [libertem.web.config.get:22] ConfigHandler.get
[2020-11-27 21:50:35,421] INFO [libertem.utils.devices.detect:48] CudaSupportError('Error at driver init: \n\nCUDA driver library cannot be found.\nIf you are sure that a CUDA driver is installed,\ntry setting environment variable NUMBA_CUDA_DRIVER\nwith the file path of the CUDA driver shared library.\n:')
```
</details>
<summary>

<summary>

Sometimes when I shut down the server, the client development server automatically closes.
<details>

```
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
[HPM] Upgrading to WebSocket
[HPM] Error occurred while trying to proxy request /api/events/ from localhost:3000 to http://localhost:9000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
Proxy error: Could not proxy request /api/events/ from localhost:3000 to http://localhost:9000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

node:events:306
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:277:15)
    at Socket.Writable.write (node:internal/streams/writable:322:11)
    at Socket.Writable.end (node:internal/streams/writable:604:10)
    at Socket.end (node:net:578:31)
    at ProxyServer.<anonymous> (/home/abi/LiberTEM/client/node_modules/react-dev-utils/WebpackDevServerUtils.js:345:9)
    at ProxyServer.emit (/home/abi/LiberTEM/client/node_modules/eventemitter3/index.js:204:33)
    at ClientRequest.onOutgoingError (/home/abi/LiberTEM/client/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:157:16)
    at ClientRequest.emit (node:events:329:20)
    at Socket.socketErrorListener (node:_http_client:478:9)
    at Socket.emit (node:events:329:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libertem-client@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libertem-client@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abi/.npm/_logs/2020-11-27T16_37_19_779Z-debug.log
```
</details>
</summary>

<summary>
In browser console

image

Redux DevTool
image

**Comment by sk1p** [comment]
> On the server, this message is being repeated [...]

Okay, that looks benign, it is only trying to reconnect, which fetches the config etc.

> Sometimes when I shut down the server, the client development server automatically closes [...]

Hmm, that one I didn't see yet. What version of nodejs are you running on? Did you install/update any npm packages?

> In browser console [403 for /api/events/]

Hmm, that's interesting. I just tried in Firefox and can reproduce the general problem, although I don't get the 403 error. It works fine in Google Chrome. Just for the sake of this PR, can you try to use another browser (chromium/chrome or something else) to see if it works there?

For fixing this problem with Firefox, maybe we have to look into updating the `create-react-app` dependencies etc.

**Comment by twentyse7en** [comment]
> Hmm, that one I didn't see yet. What version of nodejs are you running on? 

6.14.8

> Did you install/update any npm packages?

No

> Just for the sake of this PR, can you try to use another browser

No problem, It's working fine in chromium.

**Comment by sk1p** [comment]
> > Hmm, that one I didn't see yet. What version of nodejs are you running on?
> 
> 6.14.8

Ah, it might be a good idea to update once your current PRs are finished - the current long-term-supported release is 14.something

> No problem, It's working fine in chromium.

Okay, then let's defer this problem - I've logged #907 to track it.

**Comment by sk1p** [comment]
Note that in #908 I changed the way the template tests are run to re-use an existing dask cluster, this should speed up test runs quite significantly. You may have to adjust any tests that you are adding to benefit from this speedup.

**Comment by twentyse7en** [comment]
For tests, we can save the plotted image from the generated script and compare it against the image produced in the test. But here we are comparing images, any better idea @sk1p ?

**Comment by sk1p** [comment]
> For tests, we can save the plotted image from the generated script and compare it against the image produced in the test. But here we are comparing images

Why not do the tests exactly like the notebook tests, and save the results as numpy files? We don't do visual testing yet (see #55), but if you'd like to get started on that, I won't stop you :grin:

**Comment by twentyse7en** [comment]
> Why not do the tests exactly like the notebook tests, and save the results as numpy files?

In that case, the plotting part can't be tested.

> We don't do visual testing yet

Did you face any issue while trying for this?

**Comment by sk1p** [comment]
> In that case, the plotting part can't be tested.

True.

> > We don't do visual testing yet
> 
> Did you face any issue while trying for this?

Mostly, the question is, what you compare the plotting output to - for example, you could include the expected output images in the test suite. But a complication is that some details of the plot will be system-dependent. For example, if there is any text on the axes, it might look a bit different because of different versions of font rendering libraries, which will cause flaky tests, or even tests that fail on one system and pass on another.

**Comment by uellue** [comment]
With notebook copying and download working very well, I am wondering what the added value of a plain Python download is. Main point is protection of the entry point, right? We could consider simply closing this PR.

**Comment by uellue** [comment]
I'm adding to the 0.9 milestone for reassessment.

**Comment by uellue** [comment]
Closing for now since no response. At least for me, the notebook download and copy feature works perfectly already. :-)

**Pull request closed without merging**
