### PR TITLE
MRC DataSet support

### LINKED ISSUE #152: Support for MRC format
Required by Lothar Houben, Benjamin Bammes <bbammes@directelectron.com>

Important standard format for soft mater / Cryo EM

### PR DESCRIPTION
**Pull request by sk1p**
Fixes #152.

/cc @jhgee

## Contributor Checklist:

* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases

### CODE REVIEW

**Comment by AnandBaburajan** [comment]
@sk1p I think this is the new format you mentioned earlier in my PR. If I'm correct, this PR would be merged only after #793 is merged, right? I'll look into this format asap.

**Comment by sk1p** [comment]
> I think this is the new format you mentioned earlier in my PR. If I'm correct, this PR would be merged only after #793 is merged, right? I'll look into this format asap.

Haha, I'm actually not sure what format that was, but yeah, I think it would be good to have #793 merged, to enable GUI usage for 4D datasets.

The format is very similar to the raw format actually, as we can get a memory map for all data, meaning we can use the generic read ranges infrastructure etc.

> Edit: I just realised this isn't the format you were talking about:
> 
> > Btw. we will probably get support for another file format very soon, which works quite similarly, but should be simpler to understand than K2IS.

**Comment by sk1p** [comment]
> Haha, I'm actually not sure what format that was

I think it was the TVIPS format, which also has some kind of "shutter active" flag.

**Comment by sk1p** [comment]
@jhgee for the test data set you made available this seems to work fine - it seems to be inherently 3D (2D images with one "time" axis), is that correct? Are your production data sets also of this shape? Are they time series, or something like 4D STEM / pixelated STEM / scanning diffraction / ...?

If you have the time, could you test this PR with a "real" data set, also regarding performance? Thanks!

**Comment by jhgee** [comment]
> @jhgee for the test data set you made available this seems to work fine - it seems to be inherently 3D (2D images with one "time" axis), is that correct? Are your production data sets also of this shape? Are they time series, or something like 4D STEM / pixelated STEM / scanning diffraction / ...?

@sk1p, you are right. Normally, this camera mode is used to save a movie but we use it to acquire a pixelated STEM data sets. Thus, it would be nice beeing able to specify the `scan_size` as an optional input.

I can ask the camera manufacturer to add more information to the mrc file but since they are now also offering a converter to hdf5 this might be of low priority.

**Comment by sk1p** [comment]
> you are right. Normally, this camera mode is used to save a movie but we use it to acquire a pixelated STEM data sets. Thus, it would be nice beeing able to specify the `scan_size` as an optional input.

We will get the `scan_size` parameter basically for free (with a few small changes) once #793 is merged - including the `sync_offset` parameter to correct synchronization, if needed. 

> I can ask the camera manufacturer to add more information to the mrc file but since they are now also offering a converter to hdf5 this might be of low priority.

Yeah - I think it is fine having to specify the scanning parameters for now - this will get easier if we implement #768

**Comment by sk1p** [comment]
I've marked `test_copy_notebook` as flaky for now, so work on other PRs can continue, discussion on this is happening in #863

**Pull request merged**
