### PR TITLE
Restructure documentation a bit, switch to read-the-docs theme

### LINKED ISSUE #297: Separate developer installation from regular installation
Discussion with @sk1p: The difference between a developer setup and a regular installation has been a pitfall for novice users. We should move all content related to a developer setup to "Contributing" to keep the two tracks clearly separated.

### PR DESCRIPTION
**Pull request by sk1p**
Closes #297 

Other than switching to the rtd-theme, I've worked a bit on the structure, including splitting the docs into three main sections: user documentation, reference, developer docs. I've also already split the installation to remove installation from git from the normal installation instructions, which already shortens that section by a bit.

## Contributor Checklist:

* [N/A] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [N/A] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if
changes were made to the GUI)

### CODE REVIEW

**Comment by uellue** [comment]
Looks good, I like it! A lot easier to find information and navigate.

A few misc items that caught my eye, just that they don't get lost:

- [ ] LiberTEM logo with white box on blue background looks a bit strange IMO
- [ ] Acknowledgments: The end looks a bit mangled, nested entries perhaps?
- [ ] Package overview: Should contain libertem-holo

**Comment by sk1p** [comment]
> Looks good, I like it! A lot easier to find information and navigate.

Agreed!

> A few misc items that caught my eye, just that they don't get lost:
> 
> * [ ]  LiberTEM logo with white box on blue background looks a bit strange IMO

Indeed - this needs a proper fix - what do you think about making the top-left header area a neutral color (some grey tone, like pylops?), and then making the LiberTEM logo properly transparent?

> * [ ]  Acknowledgments: The end looks a bit mangled, nested entries perhaps?

It's using a class from the previous theme to clear floats, I'll take care of that.

> * [ ]  Package overview: Should contain libertem-holo

:+1: will add.

**Comment by uellue** [comment]
> Indeed - this needs a proper fix - what do you think about making the top-left header area a neutral color (some grey tone, like pylops?), and then making the LiberTEM logo properly transparent?

Sounds good! If time permits, I'll take care of it. :-)

**Comment by uellue** [comment]
We already have transparent options: https://github.com/LiberTEM/LiberTEM/tree/master/corporatedesign/logo

Would any of these work?

**Comment by sk1p** [comment]
> We already have transparent options: https://github.com/LiberTEM/LiberTEM/tree/master/corporatedesign/logo
> 
> Would any of these work?

What do you think about the "LiberTEM logo icon.svg" exported as PNG? Then we also don't have the redundancy with the "LiberTEM" label directly above the logo.

**Comment by uellue** [comment]
> Then we also don't have the redundancy with the "LiberTEM" label directly above the logo.

PyLops completely replaces the "Home" link with the logo. IMO that looks pretty good. :-)

**Comment by sk1p** [comment]
> * [ ]  Package overview: Should contain libertem-holo

The holo package is not ready yet, as the docs in that package have not been moved over from LiberTEM. We could link to the github repo for now?

**Comment by uellue** [comment]
> We could link to the github repo for now?

Sounds good! One could include that info and the fact that it is "WIP" in the description?

**Comment by sk1p** [comment]
> PyLops completely replaces the "Home" link with the logo. IMO that looks pretty good. :-)

:+1: agree, then we can use "LiberTEM logo-transparent.png" (possibly should resize a bit to not be huge)

**Comment by sk1p** [comment]
I've finished reviewing the user manual and reference sections, and even snuck in a small feature (more of an oversight: `Context.map` should pass all supported parameters down to `run_udf`, I've added `corrections` and `backends`).

Tomorrow I'll continue with the developer section, then this PR should be ready for review.

**Comment by sk1p** [comment]
I'm done with my first round through the docs - feel free to push the logo changes into this branch!

**Comment by sk1p** [comment]
Test failure is unrelated:

```
2021-01-27T11:11:02.6236819Z tests/udf/test_blobfinder.py::test_run_refine_fastmatch zero:  [64.46050747 63.92450448]
2021-01-27T11:11:02.6238501Z a:  [26.96381161 -0.31352545]
2021-01-27T11:11:02.6239166Z b:  [-0.92318253 29.34465443]
2021-01-27T11:11:02.6239797Z refining using template <class 'libertem_blobfinder.common.patterns.RadialGradient'>
2021-01-27T11:11:02.6240405Z [[ 0.22981917 -0.00503733]
2021-01-27T11:11:02.6240851Z  [ 0.25730952 -0.02890548]
2021-01-27T11:11:02.6241141Z  [ 0.02840579  0.01033434]
2021-01-27T11:11:02.6241342Z  [ 0.05589615 -0.01353381]
2021-01-27T11:11:02.6241537Z  [ 0.0833865  -0.03740196]
2021-01-27T11:11:02.6241752Z  [ 0.11087685 -0.06127011]
2021-01-27T11:11:02.6241945Z  [-0.14551722  0.00183787]
2021-01-27T11:11:02.6242997Z  [-0.11802687 -0.02203028]
2021-01-27T11:11:02.6243348Z  [-0.09053652 -0.04589843]
2021-01-27T11:11:02.6243827Z  [-0.06304616 -0.06976658]]
2021-01-27T11:11:02.6273418Z FAILED
```

```
[...]
2021-01-27T11:11:51.5700918Z >           assert np.allclose(res['b'].data[0], b, atol=0.2)
2021-01-27T11:11:51.5701260Z E           assert False
2021-01-27T11:11:51.5701847Z E            +  where False = <function allclose at 0x0000024DA984E2F0>(array([-0.72176915, 29.329283  ], dtype=float32), array([-0.92318253, 29.34465443]), atol=0.2)
2021-01-27T11:11:51.5702590Z E            +    where <function allclose at 0x0000024DA984E2F0> = np.allclose
```

**Comment by uellue** [comment]
Just using the transparent logo looks a bit strange as well since it is blue on blue.

**Comment by sk1p** [comment]
> Just using the transparent logo looks a bit strange as well since it is blue on blue.

Yeah, needs additional CSS changes.

**Pull request merged**
