### PR TITLE
Workaround for regression in numba 0.57.0

### LINKED ISSUE #1432: Numba `TypingError` with DaskJobExecutor and numba 0.57
Ran into a (local) CI error with the new numba version (python 3.10.9, LT 0.11.0 from PyPi, numba 0.57.0). While using a `DaskJobExecutor`. Same as https://github.com/numba/numba/issues/8940 found by @sk1p here https://github.com/LiberTEM/LiberTEM-live/pull/107#issuecomment-1535147339

```python
2023-05-10 15:11:02,852 - distributed.worker - WARNING - Compute Failed
Key:       _run_task-88d36aaf-0ee0-46b1-8a24-b9988c224916
Function:  _run_task
args:      (<UDFTask [<class 'libertem.udf.sum.SumUDF'>]>, <libertem.udf.base.UDFParams object at 0x7fa3a6a1a0e0>, 3, False)
kwargs:    {}
Exception: 'TypingError("Failed in nopython mode pipeline (step: nopython frontend)\\nNameError: name \'unsafe_empty_inferred\' is not defined")'
```

Can be fixed by adding

```python
import numba.cuda
```

to the end of `libertem.preload`.

### PR DESCRIPTION
**Pull request by sk1p**
Fixes #1432

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code from MIT code

### CODE REVIEW

**Review by uellue — APPROVED** [review]
LGTM! Since we import `numba.cuda` anyway on main node and workers, this shouldn't do any harm.

The test case is mostly symbolic, I guess, since `numba.cuda` will have been imported anyway at this point. But one can hope that this helps and it is most likely going into the next Numba minor release.

**Comment by sk1p** [comment]
> The test case is mostly symbolic, I guess, since `numba.cuda` will have been imported anyway at this point. But one can hope that this helps and it is most likely going into the next Numba minor release.

It actually does reproduce the issue - by creating a fresh `Context`. Because of that it's quite slow (3s on my laptop), so I'll go ahead and mark it as `slow`.

**Review by matbryan52 — APPROVED** [review]
Late to my notifications, all good from me. Thanks for the reproducer, too.

**Pull request merged**
