### PR TITLE
Version pins backport for 0.11.2

### LINKED ISSUE #1456: Point release 0.11.2?
Because of https://github.com/scikit-learn-contrib/hdbscan/issues/597, the following currently reproduces a crash:

$ conda create -n new-env python=3.11
$ conda activate new-env
$ pip install 'libertem[hdbscan]'
$ python -c 'import libertem.analysis.fullmatch'

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alex/miniconda/envs/new-env/lib/python3.11/site-packages/libertem/analysis/fullmatch.py", line 4, in <module>
    import hdbscan
  File "/home/alex/miniconda/envs/new-env/lib/python3.11/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/alex/miniconda/envs/new-env/lib/python3.11/site-packages/hdbscan/hdbscan_.py", line 40, in <module>
    FAST_METRICS = KDTree.valid_metrics + BallTree.valid_metrics + ["cosine", "arccos"]
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'builtin_function_or_method'
```

I propose we do a stable release with mostly the changes from https://github.com/LiberTEM/LiberTEM/pull/1454

* 9d1b62f7 - Pin dask to !=2023.6.1
* f9f869c4 - Pin scikit-learn to <1.3.0
* 1352955a - Fix compatibility with latest scipy 

That should ensure the `hdbscan`-using code in LiberTEM works out of the box again.

(In the long run, it might be worthwhile to clean up this code, and move the matching to `libertem_blobfinder`, too, but that's for another day probably. Then we can remove the `hdbscan` extra dependency from LiberTEM itself completely, and only have to re-release `libertem_blobfinder` in case of issues like this)

### PR DESCRIPTION
**Pull request by sk1p**
Closes #1456 

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by matbryan52** [comment]
Agreed that this makes sense. Not sure which the data check doesn't run though ?

**Comment by sk1p** [comment]
> Agreed that this makes sense. Not sure why the data check doesn't run though ?

I've struggled with this in the past, too. The pipeline definition contains the following:

```yaml
trigger:
  branches:
    include:
      - master
      - 'v*'
```

According to [the docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers), this should include builds for branches matching `v*`, but apparently it doesn't? [The wildcard docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#wildcards) also don't point to why this shouldn't match? I remember that the single quotes are also there for a reason ("documentation" in some issue on github)

**Comment by sk1p** [comment]
Now manually triggered as https://dev.azure.com/LiberTEM/LiberTEM/_build/results?buildId=2409&view=results

**Pull request merged**
