### PR TITLE
Try to speed up environment creation using uv + tox-uv

### PR DESCRIPTION
**Pull request by sk1p**
Set `uv_seed=True` to keep `pip freeze` working

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code from MIT code

### CODE REVIEW

**Comment by sk1p** [comment]
Currently still blocked by https://github.com/astral-sh/uv/issues/1539 - will have to wait for the next `uv` release. Unsure about caching (should/can we add `~/.cache/uv/` to caching?)

**Review by uellue — APPROVED** [review]
Nice, great to see RosettaSCIIO used like this!

**Pull request merged**
