### PR TITLE
Handle shapes properly in GUI

### PR DESCRIPTION
**Pull request by AnandBaburajan**
Fixes the `the autodetected shape should not contain a zero. If the nav shape can't be detected properly for 4D STEM, it should default to (y, 1)` part of #1196. I looked into the `attempting to load with an invalid shape should trigger an error or give some other feedback to the user, instead of just not doing anything` part but haven't figured out yet why the Formik error messages aren't showing up now. Maybe that part can be fixed in a separate PR?

I also refactored some code, renamed some functions and fixed [this](https://github.com/AnandBaburajan/LiberTEM/blob/master/client/src/dataset/components/TupleInput.tsx#L41) bug.

: )

Edit: also updates formik to 2.x

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated documentation for all user-facing changes
* [N/A] I have added/updated test cases
* [x] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
Hi Anand,

First of all, thank you for taking care of this!

> Fixes the `the autodetected shape should not contain a zero. If the nav shape can't be detected properly for 4D STEM, it should default to (y, 1)` part of #1196.

Great! In my testing, the fix worked well.

> I looked into the `attempting to load with an invalid shape should trigger an error or give some other feedback to the user, instead of just not doing anything` part but haven't figured out yet why the Formik error messages aren't showing up now. Maybe that part can be fixed in a separate PR?

It's possible that upgrading our JSON schema validation library (ajv) has caused this issue, or at least parts of it. Validation errors from the schema aren't properly "connected" to the right fields, and the merging of custom errors into the others is actually also broken. But even then, the errors aren't showing up for some reason. I'll have a deeper look into this.

> I also refactored some code, renamed some functions and fixed [this](https://github.com/AnandBaburajan/LiberTEM/blob/master/client/src/dataset/components/TupleInput.tsx#L41) bug.

:+1:

**Comment by sk1p** [comment]
> Validation errors from the schema aren't properly "connected" to the right fields, and the merging of custom errors into the others is actually also broken. But even then, the errors aren't showing up for some reason. I'll have a deeper look into this.

Small update: I tracked this down to `formik.touched.{nav,sig}_shape` not being set for some reason. I'll continue debugging later. Updating formik to the latest version didn't seem to have an effect, either.

**Comment by AnandBaburajan** [comment]
> First of all, thank you for taking care of this!

Hello Alex! Thank you and Dieter for everything you've done for me!

> Small update: I tracked this down to `formik.touched.{nav,sig}_shape` not being set for some reason. I'll continue debugging later. Updating formik to the latest version didn't seem to have an effect, either.

Ah. Here's what I tried doing so far. I passed `touched` in [here](https://github.com/LiberTEM/LiberTEM/blob/master/client/src/dataset/components/MIBParamsForm.tsx#L34), logged it and saw that all the fields were getting touched. Then I passed `errors` in there too, logged it and it was empty everytime for all the fields. Then I logged the `converted` [here](https://github.com/LiberTEM/LiberTEM/blob/master/client/src/dataset/validate.ts#L20) before throwing it, and it shows the expected errors in the logs. So I think the Formik errors aren't being set properly.

**Comment by sk1p** [comment]
> So I think the Formik errors aren't being set properly.

Yeah - it actually was a two-part problem. One, the errors from JSON schema validation were not passed to the right fields of the form, and two, the `TupleInput` was missing a `onBlur` handler - with the usual form fields, the validation errors are only shown once you have "touched" a form field. In Formik, touching means the field was once focused and focus was moved somewhere else. This also makes sense, as you may not want to show your user a form full of errors at the beginning, but only once the user has started to fill fields, validation errors are shown for those fields.

I've pushed a fix for this issue into your branch - feel free to test further and let me know if I missed something!

**Comment by uellue** [comment]
Error message and default value works! Thx for taking care of it. :-)

When it press "reset", it now leaves the field for the dataset name empty. For other file formats it defaults to the filename.

**Comment by uellue** [comment]
> When I press "reset", it now leaves the field for the dataset name empty. For other file formats it defaults to the filename.

Actually, in an anonymous browser window it works. Just a fluke, please ignore!

**Comment by uellue** [comment]
All in all, the form issues seem fixed now, Looks good to me, just needs CI and the rebuilt client, right?

**Review by sk1p — APPROVED** [review]

**Comment by sk1p** [comment]
> All in all, the form issues seem fixed now, Looks good to me, just needs CI and the rebuilt client, right?

:+1:

**Comment by AnandBaburajan** [comment]
> Yeah - it actually was a two-part problem. One, the errors from JSON schema validation were not passed to the right fields of the form, and two, the `TupleInput` was missing a `onBlur` handler - with the usual form fields, the validation errors are only shown once you have "touched" a form field. In Formik, touching means the field was once focused and focus was moved somewhere else. This also makes sense, as you may not want to show your user a form full of errors at the beginning, but only once the user has started to fill fields, validation errors are shown for those fields.

Ah, thanks for looking into it.

> I've pushed a fix for this issue into your branch - feel free to test further and let me know if I missed something!

Looks good to me too, and I've pushed the rebuilt client.

**Comment by sk1p** [comment]
Merging, thx again!

**Pull request merged**
