### PR TITLE
Merlin: try `ScanX` and `ScanY` from the HDR file

### LINKED ISSUE #1630: Merlin: read `ScanX` and `ScanY` from the acquisition header (`.hdr`) if available
Newer QD software, using the scan interface, writes scan information to the HDR file, so we can initialize the nav shape from that.

### PR DESCRIPTION
**Pull request by sk1p**
Fixes #1630

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code from MIT code

### CODE REVIEW

**Review by matbryan52 — COMMENTED** [review]
Looks good. Might be good to add a changelog entry to mention that this is now supported?

I will ask if there are any small data sets available with this metadata.

**Comment by sk1p** [comment]
> Looks good. Might be good to add a changelog entry to mention that this is now supported?

Thanks for having a look! Changelog entry added.
 
> I will ask if there are any small data sets available with this metadata.

Thanks, that would be great :+1: If not, I'll add some unit tests instead that exercise the added logic.

**Comment by sk1p** [comment]
Test failure looks spurious, something to fix after the 0.14 release probably:

```
tests/executor/test_delayed.py:432: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/api.py:988: in run_udf
    return self._run_sync(
.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/api.py:1281: in _run_sync
    udf_results = run_gen_get_last(_run_sync_wrap())
.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/common/async_utils.py:98: in run_gen_get_last
    result = gen.__next__()
.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/api.py:91: in __next__
    return next(self._task_results)
.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/api.py:1266: in _inner
    for udf_results in result_iter:
.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/udf/base.py:87: in __next__
    return next(self._gen)
.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/udf/base.py:[263](https://github.com/LiberTEM/LiberTEM/actions/runs/8877972975/job/24372655636?pr=1631#step:6:264)2: in _inner
    self._apply_part_result(
.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/executor/delayed.py:141: in _apply_part_result
    getattr(dest, k)[:] = getattr(merged, k)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <libertem.executor.utils.dask_inplace.DaskInplaceWrapper object at 0x7fe71c7c73e0>
key = slice(None, None, None)
value = dask.array<from-value, shape=(1,), dtype=float32, chunksize=(1,), chunktype=numpy.ndarray>

    def __setitem__(self, key, value: Union[nt.ArrayLike, Number]):
        if not np.isscalar(value) and value.size == 1:
            # Avoids deprecated Numpy behaviour of implicitly
            # extracting a scalar from an array during assignment
>           value = value.item()
E           AttributeError: 'Array' object has no attribute 'item'

.tox/py3.12/.venv/lib/python3.12/site-packages/libertem/executor/utils/dask_inplace.py:89: AttributeError
```

**Comment by matbryan52** [comment]
@sk1p I've added testdata to the data management system + a test case, these might need to be pushed into Azure pipelines ?

Then of course this needs to be rebased onto the numpy 2 branch to run again.

**Review by uellue — APPROVED** [review]
Nice, LGTM!

**Pull request merged**
