### PR TITLE
Docs fixes

### PR DESCRIPTION
**Pull request by uellue**
The removed one on symmetry was already dead for 0.12. I couldn't find an alternative source, unfortunately.

Edit: Include new link from @sk1p and a few other docs fixes

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by sk1p** [comment]
> The removed one on symmetry was already dead for 0.12. I couldn't find an alternative source, unfortunately.

There's a copy on archive.org:

http://web.archive.org/web/20221106164939/http://xrayweb.chem.ou.edu/notes/symmetry.html

**Review by sk1p — APPROVED** [review]
LGTM, archive.org link is a possibility if that content is very important

**Comment by matbryan52** [comment]
I you like I can push the changelog stuff onto this branch?

**Comment by sk1p** [comment]
> I you like I can push the changelog stuff onto this branch?

I think it's fine to have that in a separate PR

**Review by sk1p — APPROVED** [review]

**Pull request merged**
