### PR TITLE
Thorough CI if `run_slow` is set

### LINKED ISSUE #1265: CI: "thorough" tests that include normally untested Python versions
Similarly to the "slow" tests, include normally untested Python versions in a separately runnable matrix behind a configuration switch. Refs #1258

### PR DESCRIPTION
**Pull request by sk1p**
Run on more Python versions, creating a more complete matrix etc. Fixes #1265 

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by sk1p** [comment]
Coverage submission current fails because their certificate has expired (or rather, the wrong certificate has been deployed, which expired some time last month...). But the new pipeline definition does create jobs for Py37,Py38 for `data_tests` and a job for Py37 for `linux_tests`. See logs here for reference: https://dev.azure.com/LiberTEM/LiberTEM/_build/results?buildId=1867&view=logs&j=25e595a8-091d-50ed-1ba6-52ec9a5c17ec

Now to re-run without the `run_slow` parameter...

**Comment by sk1p** [comment]
> Now to re-run without the `run_slow` parameter...

Looks good, no jobs for the aforementioned combinations.

**Comment by uellue** [comment]
Looks good, slow tests and additional Python versions seem to run according to output on Azure pipelines. Merging!

**Pull request merged**
