### PR TITLE
Re-ordered acknowledgments, added some new ones

### PR DESCRIPTION
**Pull request by uellue**
Now in alphabetical order to have an objective criterion.

### CODE REVIEW

**Comment by uellue** [comment]
I couldn't reproduce the Appveyor fail on my machine. Appveyor seems to use newer packages than running `tox -e py36` on my machine.

llvmlite: 0.27.1 vs 0.27.0
numba: 0.42.1 vs. 0.42.0
numpy: 1.16.2 vs. 1.16.0

**Comment by sk1p** [comment]
Sorry, meant to reply earlier - to reproduce locally try to recreate the tox env via ’tox -r -e py36’. I agree this is not a problem with this PR, looks like it was a missing wheel for llvmlite. There appears to be a new release now, so it should be fine.

**Comment by sk1p** [comment]
I'm going to close and reopen the PR to rerun CI

**Comment by sk1p** [comment]
Thanks, merged!

**Pull request merged**
