### PR TITLE
Remove deprecated blobfinder and FeatureVecMakerUDF

### LINKED ISSUE #776: Remove deprecations for 0.7
Title says all: blobfinder, tileshape, ...

### PR DESCRIPTION
**Pull request by sk1p**
Fixes #776

blobfinder is now available as a separate package at https://github.com/liberTEM/LiberTEM-blobfinder

Instead of FeatureVecMakerUDF, you can use a sparse matrix and the `ApplyMasksUDF`.

## Contributor Checklist:

* [N/A] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by uellue** [comment]
@sk1p maybe you can also remove changelog/misc/nothing.rst? I overlooked that one when reviewing the last PR.

**Comment by sk1p** [comment]
> maybe you can also remove changelog/misc/nothing.rst? I overlooked that one when reviewing the last PR.

Sure. What do you think about removing the `pyfftw` extra dependency? Or do we still need it?

**Comment by uellue** [comment]
> What do you think about removing the `pyfftw` extra dependency?

Sounds good! What about the code in utils/threading.py? It works without pyfftw and would just make sure the thread count is correct in case someone uses it in a UDF.

**Comment by sk1p** [comment]
> Sounds good! What about the code in utils/threading.py? It works without pyfftw and would just make sure the thread count is correct in case someone uses it in a UDF.

Yeah, I would keep it, so our users (and libertem-blobfinder) don't have to think about it

**Comment by sk1p** [comment]
Actually I just saw that we already removed the pyfftw already from setup.py, so nothing to do :grin:

**Comment by sk1p** [comment]
We lost some code coverage by removing the blobfinder tests, the largest offender being `libertem.masks.sparse_template_multi_stack` and 
`libertem.masks.radial_gradient` - should we add separate unit tests?

**Comment by uellue** [comment]
> We lost some code coverage by removing the blobfinder tests, the largest offender being `libertem.masks.sparse_template_multi_stack` and
> `libertem.masks.radial_gradient` - should we add separate unit tests?

That would make sense, probably!

**Comment by uellue** [comment]
So, is this ready to be merged? :-)

**Comment by sk1p** [comment]
> So, is this ready to be merged? :-)

Still needs updated tests, didn't find time for that yet. If you have an idea how to write those feel free to take over the PR

**Comment by uellue** [comment]
OK, I'll quickly whip sth up. :-)

**Comment by sk1p** [comment]
Thanks, merging!

**Pull request merged**
