### PR TITLE
Use distributed.Client instead of distributed.asyncio.AioClient

### PR DESCRIPTION
**Pull request by uellue**
As suggested by @danpf in https://github.com/dask/distributed/issues/2537#issuecomment-466050723

Many thanks @danpf, this seems to work!

Confirmed to work with distributed==1.25.3

### CODE REVIEW

**Comment by sk1p** [comment]
Thanks for handling this! We may to also need to depend on `tornado>=5` for this to work, right?

Also another reason to work on #181 soon, which would have detected this issue for us.

**Comment by uellue** [comment]
> Thanks for handling this! We may to also need to depend on `tornado>=5` for this to work, right?

Yes, confirmed with test. See new commit in this PR for new version dependency!

> Also another reason to work on #181 soon, which would have detected this issue for us.

Yes! :-)

**Comment by sk1p** [comment]
Btw, the reason it requires tornado 5: https://www.tornadoweb.org/en/stable/releases/v5.0.0.html#highlights

> The focus of this release is improving integration with asyncio. On Python 3, the IOLoop is always a wrapper around the asyncio event loop, and asyncio.Future and asyncio.Task are used instead of their Tornado counterparts. This means that libraries based on asyncio can be mixed relatively seamlessly with those using Tornado

As I understand it, before tornado 5, interoperability between tornado and asyncio apps was limited, hence `AioClient`.

**Comment by sk1p** [comment]
Merged, thanks!

**Pull request merged**
