### PR TITLE
SEQ: UnicodeDecodeError exception

### PR DESCRIPTION
**Pull request by AnandBaburajan**
Exception for the following error which can be reproduced by loading a raw file:
`UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 452-453: il
legal encoding`

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added/updated test cases

### CODE REVIEW

**Comment by sk1p** [comment]
Good catch! It would be good to have a regression test for this; something like this should reproduce the error, right?

```python
import pytest

from libertem.executor.inline import InlineJobExecutor
from libertem.io.dataset.seq import SEQDataSet


def test_detect_unicode_error(default_raw, lt_ctx):
    path = default_raw._path
    SEQDataSet.detect_params(path, InlineJobExecutor())
```

**Comment by AnandBaburajan** [comment]
> Good catch! It would be good to have a regression test for this; something like this should reproduce the error, right?

Yes, thanks! I'll be sure to add tests next time.

**Comment by sk1p** [comment]
Thanks, merged!

**Comment by uellue** [comment]
A little nitpick after the fact: The regression test should make sure the error is triggered reliably. Does the default raw dataset do that and can we be sure it continues doing so in the future?

Anyway, I don't think it matters here, let's leave it as-is. We fix the problem properly if it crops up again. :-)

**Comment by sk1p** [comment]
> Does the default raw dataset do that
> don't know how probable it is to hit invalid unicode vs. valid unicode

I was curious and had a look into it. The way `_mk_random` currently generates test data means we get only the values from the set `{0.0, 1.0, 288.0, 2880.0}` for `default_raw`. The binary representation of those float values all start with a `'\x00'` - so the first string value, which is at offset `4`, will always be truncated to zero length and trigger the error. If we do change the function to generate values that have a larger fractional value in the binary representation (which we might want to do!), this assumption will no longer hold.

> the content of the default might change in the future since it is not designed to trigger unicode errors...

That's true. The test could be updated to reliably trigger the problem with fixed input data, for example all-zeros in the first kb of data.

**Pull request merged**
