### PR TITLE
Restart worker pool after running into error state

### LINKED ISSUE #1315: `PipelinedExecutor`: restart after exceptions
To make sure we are in a good state, restart the worker pool on exceptions. Continuation of #1311

### PR DESCRIPTION
**Pull request by sk1p**
Closes #1315

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by sk1p** [comment]
Tested with LiberTEM-live - restart works well (on Linux).

**Comment by uellue** [comment]
Fix confirmed, thx!

**Pull request merged**
