### PR TITLE
Add an eager version of `async_generator`

### PR DESCRIPTION
**Pull request by sk1p**
This is useful if there is additional work on the main thread that can happen concurrently to the work in the genreator.

## Contributor Checklist:

* [N/A] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Review by uellue — COMMENTED** [review]
If I understand correctly, this will, in effect, run UDFs in the web GUI in a separate thread since that one uses an async executor, right? From our discussion yesterday, the main benefit will be for live visualization using an inline job executor, for example for live data processing? Or does it have other uses/benefits as well?

I am just wondering if this change makes sense in LiberTEM on its own or if it belongs to a larger project/change set/... The live processing part will live in a separate project, right?

Generally, I find the code a bit hard to understand (like all async code, to be honest...). It could benefit from a high level description of what it is good for / what it achieves, and maybe some more detailed comments?

I hope this is the review you were looking for... 😆 I'm not sure what else to say about it. 🙈

**Comment by sk1p** [comment]
The `docs-check` seems to hang - looping this error:

```
2021-03-11T09:58:33.9794912Z Task exception was never retrieved
2021-03-11T09:58:33.9797120Z future: <Task finished name='Task-12' coro=<_wrap_awaitable() done, defined at /opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/asyncio/tasks.py:688> exception=BrokenPipeError(32, 'Broken pipe')>
2021-03-11T09:58:33.9798090Z Traceback (most recent call last):
2021-03-11T09:58:33.9798774Z   File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
2021-03-11T09:58:33.9799973Z     return (yield from awaitable.__await__())
2021-03-11T09:58:33.9801035Z   File "/home/vsts/work/1/s/.tox/docs-check/lib/python3.8/site-packages/distributed/core.py", line 284, in _
2021-03-11T09:58:33.9801766Z     await self.start()
2021-03-11T09:58:33.9802697Z   File "/home/vsts/work/1/s/.tox/docs-check/lib/python3.8/site-packages/distributed/nanny.py", line 298, in start
2021-03-11T09:58:33.9803449Z     response = await self.instantiate()
2021-03-11T09:58:33.9804408Z   File "/home/vsts/work/1/s/.tox/docs-check/lib/python3.8/site-packages/distributed/nanny.py", line 381, in instantiate
2021-03-11T09:58:33.9805179Z     result = await self.process.start()
2021-03-11T09:58:33.9806117Z   File "/home/vsts/work/1/s/.tox/docs-check/lib/python3.8/site-packages/distributed/nanny.py", line 552, in start
2021-03-11T09:58:33.9806885Z     self.init_result_q = init_q = mp_context.Queue()
2021-03-11T09:58:33.9807551Z   File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/multiprocessing/context.py", line 103, in Queue
2021-03-11T09:58:33.9808244Z     return Queue(maxsize, ctx=self.get_context())
2021-03-11T09:58:33.9810133Z   File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/multiprocessing/queues.py", line 47, in __init__
2021-03-11T09:58:33.9810892Z     self._wlock = ctx.Lock()
2021-03-11T09:58:33.9811527Z   File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/multiprocessing/context.py", line 68, in Lock
2021-03-11T09:58:33.9812181Z     return Lock(ctx=self.get_context())
2021-03-11T09:58:33.9812822Z   File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
2021-03-11T09:58:33.9815088Z     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
2021-03-11T09:58:33.9815898Z   File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/multiprocessing/synchronize.py", line 80, in __init__
2021-03-11T09:58:33.9816571Z     register(self._semlock.name, "semaphore")
2021-03-11T09:58:33.9817497Z   File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/multiprocessing/resource_tracker.py", line 147, in register
2021-03-11T09:58:33.9818472Z     self._send('REGISTER', name, rtype)
2021-03-11T09:58:33.9819220Z   File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/multiprocessing/resource_tracker.py", line 160, in _send
2021-03-11T09:58:33.9820573Z     nbytes = os.write(self._fd, msg)
2021-03-11T09:58:33.9821103Z BrokenPipeError: [Errno 32] Broken pipe
2021-03-11T09:58:33.9822095Z Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
2021-03-11T09:58:33.9890859Z Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
2021-03-11T09:58:33.9964695Z Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
2021-03-11T09:58:34.0504318Z Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
2021-03-11T09:58:34.0804938Z tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
2021-03-11T09:58:34.0805980Z Traceback (most recent call last):
2021-03-11T09:58:34.0807199Z   File "/home/vsts/work/1/s/.tox/docs-check/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
2021-03-11T09:58:34.0807699Z     return self.callback()
2021-03-11T09:58:34.0808406Z   File "/home/vsts/work/1/s/.tox/docs-check/lib/python3.8/site-packages/distributed/nanny.py", line 417, in memory_monitor
2021-03-11T09:58:34.0808845Z     process = self.process.process
2021-03-11T09:58:34.0809404Z AttributeError: 'NoneType' object has no attribute 'process'
```

Probably related to d1ffc223652dea700f9d7c39b318ce9fe6e1ef0f - do we need to shut down the cluster here too?

**Comment by sk1p** [comment]
> If I understand correctly, this will, in effect, run UDFs in the web GUI in a separate thread since that one uses an async executor, right?

This was already the case before, but now the workload is decoupled from the outer generator - the inner generator is allowed to run ahead of the outer generator.

>From our discussion yesterday, the main benefit will be for live visualization using an inline job executor, for example for live data processing? Or does it have other uses/benefits as well?

I think this is the main benefit right now - in case of the dask executor, it runs concurrently anyways.

> I am just wondering if this change makes sense in LiberTEM on its own or if it belongs to a larger project/change set/... The live processing part will live in a separate project, right?

I think it makes sense in LiberTEM, as it improves the `AsyncWrapper` coupling. If we put it into `libertem-live`, we will have another subtly different version of `AsyncWrapper`, which can be argued is objectively better than the main one.

> Generally, I find the code a bit hard to understand (like all async code, to be honest...). It could benefit from a high level description of what it is good for / what it achieves, and maybe some more detailed comments?

Agreed - I'll add docstrings and comments. Thanks for the feedback!

**Comment by uellue** [comment]
Looks good, merging! Thx :-)

**Pull request merged**
