### PR TITLE
Some small doc fixes

### PR DESCRIPTION
**Pull request by sk1p**
## Contributor Checklist:

* [x] I have added/updated documentation for all user-facing changes

### CODE REVIEW

**Comment by sk1p** [comment]
@uellue When you have time, can you have a look at the test failure here? Not sure if this is related to your recent PR. As this PR is not urgent, feel free to do it whenever.

**Comment by uellue** [comment]
> @uellue When you have time, can you have a look at the test failure here? Not sure if this is related to your recent PR. As this PR is not urgent, feel free to do it whenever.

Ah, this looks like an issue with conversion to float. The numbers look correct here. I'll look into this!

**Comment by uellue** [comment]
@sk1p See #559 for a proposed fix!

**Comment by sk1p** [comment]
> @sk1p See #559 for a proposed fix!

Rebased on that commit. I wonder if we can't somehow make these kind of errors better reproducible...

**Pull request merged**
