### PR TITLE
Replace docker hub link with a public one

### PR DESCRIPTION
**Pull request by sk1p**
The old one requires a login and might only work for members of the LiberTEM org on Docker Hub...

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Review by uellue — APPROVED** [review]
Good catch, thx! :-)

**Comment by uellue** [comment]
Ah, and the Docker build cache cache does work perfectly within the pipeline. :-) Previous issues were likely caused by a difference between Moellenstedt and CI.

**Comment by sk1p** [comment]
> Ah, and the Docker build cache cache does work perfectly within the pipeline. :-) Previous issues were likely caused by a difference between Moellenstedt and CI.

Nice. This shaves off 2m30s or so from the dist job :+1:

**Comment by uellue** [comment]
Also just wrote minimal project information on Docker Hub, if you'd like to take a look. :-)

**Pull request merged**
