### PR TITLE
Modifying OS-specific parts of documentation

### LINKED ISSUE #842: Idea: improve platform-specific parts of the docs
Just came across this sphinx plugin: https://sphinxcontrib-platformpicker.readthedocs.io/en/stable/usage.html - this looks nice and could clean up some platform-specific parts of our docs

### PR DESCRIPTION
**Pull request by sayandip18**
Fixes #842 

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if
changes were made to the GUI)

### CODE REVIEW

**Comment by uellue** [comment]
Regarding the CI failure: That's a known issue, see #883. We can ignore it here.

**Comment by uellue** [comment]
Hi Sayandip, thanks again for the PR and sorry for the delay! From a user's perspective it looks good this way. However, large parts of the documentation are now duplicated for the platforms. That increases the maintenance and QA effort.

Is there a way to change specifically only the parts that are actually different without having buttons all over the text, or at least avoid the duplication of MacOS and Linux instructions that are largely identical?

**Comment by sk1p** [comment]
> Regarding the CI failure: That's a known issue, see #883. We can ignore it here.

This is now be fixed, if you rebase to current master the error should be gone.

**Comment by sayandip18** [comment]
> Is there a way to change specifically only the parts that are actually different without having buttons all over the text, or at least avoid the duplication of MacOS and Linux instructions that are largely identical?

Yes, there is. As far as I remember, I had kept it only for parts which are slightly dissimilar. I'll give it a look soon and reduce it even further if possible.

**Comment by uellue** [comment]
This PR is now getting a bit stale. @sk1p already improved the situation by moving the "dev install" part to a separate section. Maybe we can just close here and leave it be? Assigning to 0.9 for reassessment.

**Comment by uellue** [comment]
Closing since no feedback so far. Thx @sayandip18 for your efforts!

**Pull request closed without merging**
