### PR TITLE
Make the `correct` tests a bit more strict

### PR DESCRIPTION
**Pull request by sk1p**
Don't accidentally catch exceptions

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases

### CODE REVIEW

**Comment by sk1p** [comment]
Hm, the Mac OS X test once again failed - should we maybe allow failures for them? /cc @uellue

**Comment by uellue** [comment]
> Hm, the Mac OS X test once again failed - should we maybe allow failures for them? /cc @uellue

Did you restart it? I can't seem to find a failed test... Do you have a link?

**Comment by sk1p** [comment]
Yes, I restarted - sadly the old logs seem to be erased in that case. IIRC the error was that the scheduler couldn't bind to the given address (already in use) - and then it hit another issue in distributed (https://github.com/dask/distributed/pull/3912).

I have a hunch what the problem could be: the local cluster destruction was a bit impatient and had a short timeout. I'll increase the timeout and actually not swallow the exception in that case, let's see if that improves things.

**Comment by uellue** [comment]
👍 Fingers crossed! :-)

**Comment by uellue** [comment]
Nice, merged!

**Pull request merged**
