### PR TITLE
Fix notebooks

### PR DESCRIPTION
**Pull request by uellue**
* Mitigation for https://github.com/dask/distributed/issues/7471 picked from #1207
* Rerun notebooks and remove ";". Somehow the notebook tests expect an output despite the ";". I like it better without ";" anyway.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by matbryan52** [comment]
";" in the notebooks is me, sorry! It seemed like we were catching and filtering output using `nbval_sanitize` when adding the ; would suppress the matplotlib stuff Strange that the notebook tests still expect output...

**Comment by uellue** [comment]
> ";" in the notebooks is me, sorry! It seemed like we were catching and filtering output using `nbval_sanitize` when adding the ; would suppress the matplotlib stuff at the source. Strange that the notebook tests still expect output...

Yes, that looks like a bug in the test routines to expect an output there. Probably we were dealing with "opposing bugs" here that first require the ";" and then break with the ";". I'll work on a reproducer and report it to nbval. :-)

**Comment by uellue** [comment]
https://github.com/computationalmodelling/nbval/pull/195

**Comment by uellue** [comment]
I'll just go ahead and merge so that I can also merge #1381 without a guaranteed build failure. :-)

**Pull request merged**
