### PR TITLE
Add support for scipy.sparse.{coo,csr,csc}_array

### PR DESCRIPTION
**Pull request by uellue**
...through `sparseconverter>=0.4.0`.

* Deactivate for `ApplyMasksUDF` since matrix multiplication with sparse.pydata is not implemented
* Deactivate for `LogsumUDF` analog to SciPy sparse matrices

Impact on LiberTEM consumers is TBD. The documentation already warns that tests with each backend are required and that `UDF.BACKEND_ALL` may change.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by uellue** [comment]
LiberTEM-live integration will fail until https://github.com/LiberTEM/LiberTEM-live/pull/165 is released

**Review by sk1p — APPROVED** [review]
LGTM!

**Pull request merged**
