### PR TITLE
Add pipeline with data access

### LINKED ISSUE #86: Test files for datasets
We need better test coverage for datasets. This could be done by having a small (<1MB?) example file for each file format we support in our repository, and testing all relevant functions on real data.

- [ ] MIB (different bit depths, different partitioning (number of frames per `.mib` file)) #129 
- [x] RAW (different variants, including endian-ness #144 ,can easily be generated)
- [x] HDF5 (can easily be generated)
- [ ] BLO 
- [ ] K2IS #63 #109 
- [ ] FRMS6  #155
- [ ] MRC #152 
- [ ] Norpix Seq #153 
- [ ] TIA SER/EMI

For K2IS we should also have some additional files that exhibit the weird corner cases of the format.

### PR DESCRIPTION
**Pull request by sk1p**
Fixes #86. The test data is provided as a bind mount at `/data/` (currently pointing to a directory owned by my user, where I put the private test data to mirror my local setup, but that can be changed).

### CODE REVIEW

**Comment by sk1p** [comment]
I'm going to merge this now, to test if the build still doesn't run on `master` - @uellue please let me know if you are happy with the comment-based trigger for running I/O tests.

**Comment by uellue** [comment]
The comment-based method is supposed to prevent running arbitrary code on our agent via a PR, right? How is this authenticated and authorized? Can I trigger this, too?

I tried to access the Azure Pipelines details of LiberTEM, but couldn't:

```
{"$id":"1","innerException":null,"message":"TF400813: The user 'Windows Live ID\\d.weber@materials-scientist.com' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

**Comment by sk1p** [comment]
> The comment-based method is supposed to prevent running arbitrary code on our agent via a PR, right?

Right.

> How is this authenticated and authorized?

Authentication: the comment metadata includes the github username, so your login into github is the authentication

Authorization: the comment functionality is limited to team members, which are defined as users with Write permissions. The user [needs to set his membership to public](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#run-pull-request-validation-only-when-authorized-by-your-team) though.

> I tried to access the Azure Pipelines details of LiberTEM, but couldn't: [...]

I'll add you as an admin to the Azure DevOps organization. The project is set to public visibility, but I guess that doesn't make all settings public, too.

**Comment by sk1p** [comment]
I think your comment above didn't trigger a pipeline run, because the branch was already deleted. Could you re-try on #912?

**Comment by uellue** [comment]
> I think your comment above didn't trigger a pipeline run, because the branch was already deleted. Could you re-try on #912?

Works! 👍 😄

**Comment by sk1p** [comment]
Great! :+1:

**Pull request merged**
