### PR TITLE
Fix cross-platform dataset opening

### LINKED ISSUE #530: EMPAD: problems when opening via remote executor
Fails because of the incompatible configuration Local Windows <> Remote Linux (`no module named 'nt'`). Need to find a suitable fix for this - proposals welcome!

### PR DESCRIPTION
**Pull request by uellue**
Closes #530
Refs #727 

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated test cases

### CODE REVIEW

**Comment by uellue** [comment]
We should test this thoroughly as part of the release testing

**Comment by AnandBaburajan** [comment]
@uellue Can this PR wait till https://github.com/LiberTEM/LiberTEM/pull/700 is merged? Thanks!

**Comment by sk1p** [comment]
> @uellue Can this PR wait till #700 is merged? Thanks!

Sure thing!

**Comment by sk1p** [comment]
The CI failure was caused by a flaky dd test, re-running the job "fixed" it. PR looks good, thanks!

**Pull request merged**
