### PR TITLE
Final adjustments for JOSS paper

### PR DESCRIPTION
**Pull request by uellue**
* Remove performance claims compared to Spark and dask.distributed -- refs #198
* Suggestions by @majensen, thx! :-)

- [x] Update author list

@AnandBaburajan @twentyse7en @abiB27 @bdalevin @Iamshankhadeep @saisunku you started contributing to LiberTEM after the first draft of this paper was submitted. Since you became co-creators of LiberTEM and the paper now references the latest release 0.5.0, per our authorship policy you are cordially invited to be co-authors of this paper!

See also https://github.com/openjournals/joss-reviews/issues/2006 for the open review.

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes

### CODE REVIEW

**Comment by uellue** [comment]
... and @sayandip18, you are of course also invited to be co-author, sorry that I missed this!

**Comment by AnandBaburajan** [comment]
I've read the paper and I'd be glad to be a co-author, thanks!

**Comment by twentyse7en** [comment]
Looks good to me. Thanks for the invitation, I'm happy to be part of this.

**Comment by saisunku** [comment]
@uellue thank you for the offer but I don't think I have contributed enough to warrant authorship, so please don't include me.

**Comment by uellue** [comment]
@AnandBaburajan @twentyse7en Do you have an [Orcid](https://orcid.org/) or would you like to create one? That is an unique ID that helps to keep track of your publications over time, in particular when other researchers have the same name or when a name changes.

**Comment by uellue** [comment]
@saisunku Ok, thank you for the feedback and again for your contributions. If you change your mind let me know!

**Comment by AnandBaburajan** [comment]
> Do you have an [Orcid](https://orcid.org/) or would you like to create one?

@uellue 0000-0002-2870-366X

**Comment by uellue** [comment]
> > Do you have an [Orcid](https://orcid.org/) or would you like to create one?
> 
> @uellue 0000-0002-2870-366X

Thx! :-)

**Comment by twentyse7en** [comment]
Mine 0000-0001-5045-5650

**Comment by uellue** [comment]
@AnandBaburajan In the Orcid, "Government Engineering College Sreekrishnapuram" is given as affiliation. I've updated creators.json and the paper accordingly. Could you please have a look that the current version is correct? :-)

**Comment by AnandBaburajan** [comment]
> @AnandBaburajan In the Orcid, "Government Engineering College Sreekrishnapuram" is given as affiliation. I've updated creators.json and the paper accordingly. Could you please have a look that the current version is correct? :-)

Yes, the changes are okay. :)

**Comment by uellue** [comment]
@twentyse7en many thanks! I've updated your affiliation as well. Could you check if it is OK now?

@all this is the latest preview: https://res.cloudinary.com/hju22ue2k/image/upload/v1591349530/xxm0zq8xwphrtfdvoql5.pdf

If you like, have a look! I'll merge soon.

**Comment by twentyse7en** [comment]
> @twentyse7en many thanks! I've updated your affiliation as well. Could you check if it is OK now?

Looks good, Thx : )

**Pull request merged**
