### PR TITLE
Include @woozey in creators because of binning prototype commit

### PR DESCRIPTION
**Pull request by uellue**

### CODE REVIEW

**Comment by uellue** [comment]
@woozey Thx for the fix! This is a good opportunity to improve the process to guide people towards editing the JSON files and using those as the only source of truth, see the last commit.

**Comment by sk1p** [comment]
Hm, maybe the `.gitignore` file could actually ignore the `.rst` files, so they don't get accidentally added to the repo. I guess right now it only serves the purpose of keeping the directory in git? 

Other than that it looks good!

**Comment by uellue** [comment]
> Hm, maybe the `.gitignore` file could actually ignore the `.rst` files, so they don't get accidentally added to the repo.

Done! :-)

**Comment by sk1p** [comment]
Perfect, thanks!

**Pull request merged**
