### PR TITLE
Update frontend libraries

### LINKED ISSUE #1046: Review https://github.com/LiberTEM/LiberTEM/security/dependabot and update dependencies
Deferred from 0.7 release, but still TODO to avoid bitrot.

### PR DESCRIPTION
**Pull request by sk1p**
Two main updates:

- `eslint` is now used instead of tslint, as tslint was deprecated and development moved over to eslint
- `react-scripts` was updated to the current version

`semantic-ui-react` was also updated to the current version.

To make the build and lint pass, quite a lot of changes were needed, mostly related to fixing types, and also updating to best-practice idioms (like use of arrow-function syntax, omitting the return statement in case of single-statement functions etc.)

I also snuck in a small change of the nav/sig labels in the open dialog to explain the order of dimensions.

Fixes #1046

Note: client is not rebuilt yet, so if you want to try this pr, you need to `npm install && npm run start`. 

## TODO

- [x] do another update of dependencies, as there have been some releases in the meantime...

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated documentation for all user-facing changes
* [N/A] I have added/updated test cases
* [x] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
This should now be ready for review/check-in - if no one has feedback, I'll re-build client and merge some time this week.

**Comment by uellue** [comment]
Looks good, works on my system, thx for taking care of it! Should be ready to merge as soon as CI passed.

**Comment by uellue** [comment]
Merging! :-)

**Pull request merged**
