### PR TITLE
Update release procedure

### PR DESCRIPTION
**Pull request by sk1p**
* Update and re-structure release checklist
* No longer use zenodo sandbox and test.pypi.org; instead upload directly to production deployments (streamlines things a bit, and makes installing an RC easier; also probably more stable, especially regarding wipes of the zenodo sandbox)
* Add missing Python 3.12 classifier

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code from MIT code

### CODE REVIEW

**Review by matbryan52 — APPROVED** [review]
I like the changes to the release checklist. I would question whether these two are still practical given the number of datasets and the potential number of ways the system could fail:

```
* [ ] Check what happens when trying to open non-existent files by scripting.
    * [ ] Proper understandable error message? TODO automate?
* [ ] Check what happens when opening all file types with bad parameters by scripting
    * [ ] Proper understandable error message? TODO automate?
 ```

We could say that automating these tasks should actually happen for 0.14 - I will try to write a `/data` test which actually collects a bunch of error messages that a human could quickly read over...

**Comment by sk1p** [comment]
>  I would question whether these two are still practical given the number of datasets and the potential number of ways the system could fail:

Agreed...

> We could say that automating these tasks should actually happen for 0.14

:+1: yeah, not automating something just means it will be unreliably (or not) tested before releases.

**Review by uellue — APPROVED** [review]
:+1: :+1: :+1:

**Pull request merged**
