### PR TITLE
Update screenshots - First part

### PR DESCRIPTION
**Pull request by twentyse7en**
Updated screenshots in usage documentation.
completed first part.
ISSUE #591

## Contributor Checklist:

* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution

### CODE REVIEW

**Comment by twentyse7en** [comment]
@uellue can you verify the first part.

**Comment by sk1p** [comment]
The `pick_frame` one being black/empty is actually a bug that is fixed in #606 - if you retry this with LiberTEM from master, you should be able to see diffraction patterns for all possible positions.

**Comment by uellue** [comment]
@twentyse7en Looks good already, many thanks!

For further improvement, perhaps you could make the browser window narrower so that it doesn't show so much blank space left and right? That way the text will hopefully appear a bit larger, too.

Next step would then be to include documentation on stddev and ROI. Was @sk1p 's explanation of stddev  in #591 clear? Essentially, it is a measure of how much a specific pixel changes between frames. A pixel that is always the same brightness will get a value of zero, and a pixel that fluctuates a lot will get a high value.

**Comment by twentyse7en** [comment]
Removing the blank space would be good. I'm not familiar with 4D datasets, I should better read concepts page first and would ask questions if I don't get it.

**Comment by uellue** [comment]
The screenshots look good now! 👍

**Comment by sk1p** [comment]
@twentyse7en :+1: - do you want to do the second part in this PR, or is this ready for merging?

**Comment by twentyse7en** [comment]
It would be better if someone else do second part, I'm having series exam on my college.

**Comment by sk1p** [comment]
@twentyse7en thanks for the PR, merged! :tada:

**Pull request merged**
