### PR TITLE
Add more mypy type annotations

### PR DESCRIPTION
**Pull request by sk1p**
## Contributor Checklist:

* [N/A] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
CI needs some work - I'll possibly move this over to pre-commit.

**Comment by sk1p** [comment]
@uellue this should be ready to be merged. When you have time, could you quickly have a look at the documentation changes (and try the pre-commit changes on windows)? The first mypy run is possibly a bit slower, as it builds up a cache that is used in subsequent runs.

The type annotations themselves are subject to change and should improved over time, as we add more files that are checked.

**Review by uellue — APPROVED** [review]
LGTM, thank you for taking care of it! As discussed some changes in the commits that I just pushed. :-)

**Comment by sk1p** [comment]
> As discussed some changes in the commits that I just pushed. :-)

Thanks for the review, much appreciated!

**Pull request merged**
