### PR TITLE
Support for nD HDF5 files

### PR DESCRIPTION
**Pull request by uellue**
The HDF5 dataset seems to still have an assumption of being 4D hardcoded.
As an example, libertem.io.dataset.hdf5.H5DataSet.get_partitions() works
with a 4D origin.

The same holds for libertem.io.dataset.base.DataSet.partition_shape() and
libertem.io.utils.get_partition_shape().

LiberTEM should support files with any shape and at least two dimensions.

See also #441

Thx @robertbuecker for reporting!

## Contributor Checklist:

* [x] I have added myself to [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated test cases

### CODE REVIEW

**Comment by uellue** [comment]
@sk1p Can I assign this to you? This is a bit above my experience level with DataSet.

**Comment by sk1p** [comment]
Sure, I'll take care of it.

**Comment by sk1p** [comment]
@uellue do you want to review? From my side, this is ready for check in

**Comment by uellue** [comment]
Thank you, fix confirmed! :-)

**Pull request merged**
