### PR TITLE
Work around a hang related to Numba in GMS

### PR DESCRIPTION
**Pull request by uellue**
Thx @sklam for the decisive test case!

Still unclear why it hangs when running directly in the background thread,
but this seems to work. :shrug:

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if
changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Review by sk1p — COMMENTED** [review]
Looks good. Just to confirm, whatever fixes the problem with `numba` does _not_ fix the multiprocessing issues?

**Comment by uellue** [comment]
> Looks good. Just to confirm, whatever fixes the problem with `numba` does _not_ fix the multiprocessing issues?

Unfortunately not: `Can't pickle local object 'main.<locals>.test'`

**Comment by sk1p** [comment]
> Unfortunately not: `Can't pickle local object 'main.<locals>.test'`

Is the error similar / the same when using our `DaskJobExecutor`?

**Comment by uellue** [comment]
> Is the error similar / the same when using our `DaskJobExecutor`?

In that case, it seems that Dask.Distributed fails to bring up the workers. I get an error message "The system cannot find the file specified".

**Comment by sk1p** [comment]
> In that case, it seems that Dask.Distributed fails to bring up the workers. I get an error message "The system cannot find the file specified".

Okay. Should we maybe add a second example that connects to a LiberTEM cluster that is running outside of GMS, with directions on how to start the external scheduler and workers? Otherwise we will only have underwhelming single-threaded performance...

**Comment by uellue** [comment]
> > In that case, it seems that Dask.Distributed fails to bring up the workers. I get an error message "The system cannot find the file specified".
> 
> Okay. Should we maybe add a second example that connects to a LiberTEM cluster that is running outside of GMS, with directions on how to start the external scheduler and workers? Otherwise we will only have underwhelming single-threaded performance...

Good point! This is confirmed to work. We might also remove the note that distributed operation is experimental and put in an instruction how to bring up a cluster, since it works pretty nicely with `libertem-worker` these days. :-)

**Review by sk1p — APPROVED** [review]
LGTM!

**Pull request merged**
