### PR TITLE
Fix pyxem tests

### PR DESCRIPTION
**Pull request by sk1p**
To fix our tests with data access. Extracted from #1170 (without the hyperspy integration notebook, of course). author: @uellue 

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [ ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by uellue** [comment]
The build failure is introduced by `sphinx-issues==3.0.0`. Still investigating if we can fix it...

**Comment by uellue** [comment]
https://github.com/sloria/sphinx-issues/issues/125

**Comment by sk1p** [comment]
> The build failure is introduced by `sphinx-issues==3.0.0`. Still investigating if we can fix it...

Sigh, maybe pin to `<3` for now?

**Comment by uellue** [comment]
Ok, can I push that?

**Comment by sk1p** [comment]
> Ok, can I push that?

Sure, go ahead!

**Pull request merged**
