### PR TITLE
Use Python 3.9 for the AppImage

### PR DESCRIPTION
**Pull request by sk1p**
## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [N/A] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
Ah, I see the important part of the changelog entry was already created in #1034, rest might need to be integrated there.

**Comment by uellue** [comment]
> Ah, I see the important part of the changelog entry was already created in #1034, rest might need to be integrated there.

Maybe it would be easiest to create a TODO item in #1034 to amend the changelog and remove the changelog entry in this PR?

**Comment by sk1p** [comment]
> Maybe it would be easiest to create a TODO item in #1034 to amend the changelog and remove the changelog entry in this PR?

Good idea, done.

**Comment by uellue** [comment]
Huh, CI doesn't like us? Closing and reopening...

**Comment by sk1p** [comment]
> Huh, CI doesn't like us? Closing and reopening...

Fastly CDN is down, affecting GitHub, PyPi, and many others...

**Comment by sk1p** [comment]
https://status.fastly.com/

https://status.python.org/

**Comment by uellue** [comment]
> https://status.fastly.com/
> 
> https://status.python.org/

Thx! :-)

**Comment by sk1p** [comment]
Fastly is now up again, and CI passes. I've tested the AppImage locally and it seems to work fine.

**Comment by uellue** [comment]
> Fastly is now up again, and CI passes. I've tested the AppImage locally and it seems to work fine.

Perfect, merging then! :-) Thx!

**Pull request merged**
