### PR TITLE
Undo 55c8160305b1a42f154151d1a8e2a5bda562380e to see if this is still…

### PR DESCRIPTION
**Pull request by uellue**
… necessary

See #370

## Contributor Checklist:

* [x] I have added myself to [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)

### CODE REVIEW

**Comment by sk1p** [comment]
Hmm, we need to be careful with this change - if I remember correctly, having more than one thread means that some resources will be created per thread by dask.distributed - need to look out for debug output in a stress test, for example when running multiple analyses at the same time via the web API (try for example picking while another, or multiple other, analyses are running).

**Comment by uellue** [comment]
Yes, it should not go into 0.3. We can perhaps merge it after the release and stress-test it a bit in the real world? At least on my system, running parallel analyses is no issue. The file browsing behavior https://github.com/LiberTEM/LiberTEM/issues/186#issuecomment-534518019 seems to be improved by this change, at least on my system.

By the way, is there a reason to limit this to four and not leave it at the default? I couldn't notice much of a difference on my system when using it in an IO-limited scenario. It is really hard to judge and non-deterministic.

**Comment by uellue** [comment]
Ok, CI answered the question about the default thread count.

**Comment by sk1p** [comment]
> Ok, CI answered the question about the default thread count.

:+1: 

For reference: https://travis-ci.org/LiberTEM/LiberTEM/jobs/624223065 - my guess would be that dask distributed creates a new client, or at least a new connection, per thread. So it uses more fds than usually, and trips the respective test.

> I couldn't notice much of a difference on my system when using it in an IO-limited scenario. It is really hard to judge and non-deterministic.

Because the threading in this case is not introduced for performance reasons, but rather to isolate the asyncio loop.

**Comment by sk1p** [comment]
> Because the threading in this case is not introduced for performance reasons, but rather to isolate the asyncio loop.

Closing the PR for this reason, having only 1 thread here makes sense.

**Pull request closed without merging**
