### PR TITLE
Tiling scheme reorganization

### PR DESCRIPTION
**Pull request by sk1p**
Negotiate the tiling scheme once, to reduce overheads for both iteration and live use cases

# TODO
- [x] fix failing test case

## Contributor Checklist:

* [N/A] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [N/A] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
The failing test case: `tests/io/test_tiling_negotiation.py::test_get_scheme_upper_size_roi`

Because we aren't doing the negotiation per-partition anymore, we can't take the "local" `roi` of the partition into account when building the scheme. So instead of a tile shape of `(3, 144, 144)`, we get something like `(65, 28, 144)` - meaning we have about 5 times as many tiles in this case. 

@uellue do you remember if there is a common case where this happens, or if this was just an edge case / worst case which we handled because we could?

I think the proper fix for this is to just grow the partition in case of a sparse `roi`, in order to always have deep enough tiles.

**Comment by uellue** [comment]
@sk1p The ROI can be really anything. Rebalancing the partitioning so that we have an equal number of frames per partition and the optimal number of partitions would be perfect. :-) For the resistive switching example that should bring significant benefits on large machines because the file is not very large, meaning one partition per core, and the number of frames per partition is probably all over the place with the ROI shape. That means many cores will just be idle and the total time is the time for the largest partitions.

That feels pretty close to #382, right? Would that be within reach?

**Comment by sk1p** [comment]
> That feels pretty close to #382, right? Would that be within reach?

I'll have a look into it - I think it makes sense to tackle this now.

**Comment by uellue** [comment]
> That feels pretty close to #382, right? Would that be within reach?

In more detail, it would mean we calculate the partitioning for each run and have non-uniform partition size, which means we are pretty close to just decide on the fly how large they are. We should calculate the optimal tiling scheme for the largest partition size, since that reduces overheads for fast algorithms, while slower algorithms are probably less affected if the tiles are smaller than expected.

**Comment by sk1p** [comment]
> we are pretty close to just decide on the fly how large they are.

That's what I would aim for, yes.

> We should calculate the optimal tiling scheme for the largest partition size, since that reduces overheads for fast algorithms, while slower algorithms are probably less affected if the tiles are smaller than expected.

Agreed.

So regarding this PR, I would `xfail` the offending test, then it should be ready to be merged.

**Comment by uellue** [comment]
I did some benchmarks and the result is a bit inconclusive for the UDF overheads because of high standard deviation. Since the main point is code re-organization anyway and it is at least not getting slower, so it is OK! :-)

Generally LGTM! :-)

**Pull request merged**
