### PR TITLE
Remove deprecated Job interface

### LINKED ISSUE #549: Remove deprecated Job functionality
All currently implemented Job functionality can, in principle, be expressed through the UDF API. By only having one interface we can reduce the complexity of LiberTEM. Furthermore, the ApplyMasksJob functionality can be useful as a base class and example for other UDFs, and dtype support should be added to UDFs in any case.

Steps:

- [x] Implement basic ApplyMasksJob functionality through an UDF PR #550 
- [x] Implement basic PickFrameJob functionality through an UDF #550
- [x] Port dtype support to UDF interface PR #550 
- [x] Copy and adapt all Job-related tests for the new UDFs #550
        --> This should be covered by the existing UDF tests, tests for the new UDFs and tests through the Analyses
- [ ] Benchmarking, profiling and optimization to make sure the new system is at least on par performance-wise.
     --> This requires more systematic tests under controlled conditions. In particular the impact of mmap should be tested on madmax nodes since they are more sensitive to memory transfer bottlenecks than moellenstedt.
- [x] Specific performance regression: Pick mode on HDF5. Discussion with @sk1p: The ROI implementation of HDF5 datasets should be improved. Fix committed in #567 
- [x] Port MasksAnalysis to new UDF #550 
- [x] Port remaining Analysis classes to the new UDFs #550 
- [x] Investigate if there are any applications that could be implemented through the Job interface, but not through UDFs.
- [x] Update examples #576 
- [x] Update documentation, including a migration guide, depreciation warnings and a schedule for retirement of the Job API #577 
- [x] Trigger depreciation warnings when using the Job API #577 
- [ ] Remove Job API after the depreciation period, possibly with 1.0 release.

### PR DESCRIPTION
**Pull request by sk1p**
Fixes #549

* libertem.api:
    * Remove `Context.create_*_job`
    * Remove capability to run `Job` in `Context.run`
* libertem.analysis:
    * Remove `get_results` and `get_job` from `Analysis` class
    * Default to `Analysis.TYPE = 'UDF'`
    * throw error when a `BaseAnalysis` with `TYPE = 'JOB'` is instantiated
* Remove `get_results` and `get_job` from `Analysis` implementations
* Clean up tests: remove job-only tests, port others to UDF interface

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if
changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
> * [ ]  port radial fourier analysis to natively use results from the UDF

@uellue what do you think about keeping the radial fourier analysis as-is? If we remove the transpose, we change the `raw_results` of the `ResultSet`, so we would either have to accept that the result is different, or transpose anyways. Thoughts?

**Comment by uellue** [comment]
> @uellue what do you think about keeping the radial fourier analysis as-is?

+1 keeping it as-is. We can re-evaluate in case the current way creates a real problem for users.

**Comment by sk1p** [comment]
Great! I'll remove the `FIXME` then - from my side this should be ready.

**Review by uellue — APPROVED** [review]
Looks great and still seems to work. Thx for taking care of it! 👍

**Pull request merged**
