### PR TITLE
Rearrange slow tests; mitigation for https://github.com/dask/distributed/issues/6776

### PR DESCRIPTION
**Pull request by uellue**
## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [ ] No import of GPL code from MIT code

### CODE REVIEW

**Comment by uellue** [comment]
@sk1p can you trigger the slow tests for this one?

**Review by sk1p — APPROVED** [review]
LGTM!

**Comment by sk1p** [comment]
> can you trigger the slow tests for this one?

Done - fixed two small issues in the pipeline definition, now tests succeed and it looks like there are no skips in the data tests. Looks good to go!

**Pull request merged**
