### PR TITLE
Deprecate Python 3.6 support

### LINKED ISSUE #1369: Sunsetting Python 3.6 support?
It might be time to drop support for Python 3.6:

* Many of our dependencies no longer support Python 3.6
* CI test pipelines for 3.6 are difficult to set up since one has to search for OS images that still have it
* Installation with `pyproject.toml` is only supported in 3.7 or newer.
* Current versions of Gatan Microscopy Suite use Python 3.7. 
* Dectris support in LiberTEM-live already requires Python 3.7 for the Rust receiver component.
* Dask array integration only works partially with 3.6.

Are there any software environments where Python 3.6 support is still required? If yes, please comment! Otherwise we are tending towards dropping it for the next release. This will allow us to use `pyproject.toml` for #1207 to spin out the conversion as new package in https://github.com/LiberTEM/sparseconverter

## TODO items

- [ ] Any reasons to keep 3.6?
- [ ] Update version requirement in setup.py
- [ ] Changelog
- [ ] Release message

### PR DESCRIPTION
**Pull request by uellue**
Closes #1369 

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [N/A] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-data` passed
* [x] No import of GPL code from MIT code

### CODE REVIEW

**Comment by uellue** [comment]
Hm,  `[test_progress_inline_fasttime](https://dev.azure.com/LiberTEM/LiberTEM/_build/results?buildId=2105&view=logs&j=25e595a8-091d-50ed-1ba6-52ec9a5c17ec&t=e3de3002-b73c-559f-d7ce-30aa4bd2811b&l=144)` was flaky on my system, too. Not sure what is going on there?

**Review by sk1p — APPROVED** [review]

**Pull request merged**
