### PR TITLE
Prevent h5py locking up on some files

### LINKED ISSUE #1231: Reading from write-protected files
Reading sealed files in the ER-C data management with LiberTEM fails for unknown reasons. To be investiaged further, no time now.

### PR DESCRIPTION
**Pull request by uellue**
The file /er-c-data/adhoc/in_situ_diff/2022-03-17 EMPAD live zinc growth/raw/20220317_Shiv/01_1_before liquid/01_1_before liquid.xml
locks up h5py.File(...) hard.

HDF5 files SHOULD have a reliable file magic. At least all HDF5 based test files
were recognized.

Closes #1231 

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [N/A] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases
* [N/A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-data` passed

### CODE REVIEW

**Comment by uellue** [comment]
@sk1p it looks like the environemnts have to be rebuilt? How can that be triggered?

**Comment by uellue** [comment]
Upon further investigation, the issue is caused by the HDF5 library trying to obtain a lock on the file. See also https://iffgit.fz-juelich.de/weber/data-management-system/-/issues/31 (private repository).

Not sure if this change is still an improvement?

**Comment by uellue** [comment]
Discussion with @sk1p:

The locking issue is resolved, it was an NFS misconfiguration. `python-magic` expects specific DLLs on Windows that may or may not be present. We'll close this for now and may implement our own "magic" check for file formats we support if this becomes an issue again.

**Comment by sk1p** [comment]
> > it looks like the environemnts have to be rebuilt? How can that be triggered?
> 
>  enter `refs/pull/1232/merge` as commit

Actually, that needs to be entered in the "branch/tag" field, not in the commit field - otherwise, the checkout will fail (see for example https://dev.azure.com/LiberTEM/LiberTEM/_build/results?buildId=1740&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e )

**Pull request closed without merging**
